(()=>{
'use strict';
const KEY='hos150v12', H=3600000, FIVE=300000;
const $=id=>document.getElementById(id);
const now=()=>Date.now();
const fresh={status:'OFF DUTY',currentStart:now(),segments:[],events:[],pos:null,base:null,cycle:60,cycleRemaining:null,shiftStart:null,records:[],docs:[],inspect:{pre:{},post:{}},route:null,routeStart:null,routeEnd:null,routeMiles:null,routeMinutes:null,autoMode:'prompt',profile:{driver:'',carrier:'',dot:'',unit:'',vin:'',trailer:''},fuel:[],expenses:[],maintenance:[],loads:[],pod:[],morning:false};
let S=Object.assign({},fresh,JSON.parse(localStorage.getItem(KEY)||'{}'));
S.profile=Object.assign({},fresh.profile,S.profile||{});
let watch=null,stopSince=null,map=null,me=null,circle=null,line=null,rmap=null,rme=null,rcircle=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const fmt=x=>{x=Math.max(0,x||0);let m=Math.floor(x/60000);return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')};
const active=s=>(S.segments||[]).reduce((n,x)=>n+(x.status===s?Math.max(0,x.end-x.start):0),0)+(S.status===s?Math.max(0,now()-S.currentStart):0);
const air=(a,b,c,d)=>{const R=3958.761,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
function ev(status,source='DRIVER',note='Duty status change'){S.events.unshift({time:new Date().toISOString(),status,source,note,loc:S.pos?`${S.pos.lat.toFixed(5)},${S.pos.lon.toFixed(5)}`:'GPS unavailable'});S.events=S.events.slice(0,1000)}
function duty(s,src='DRIVER'){if(s===S.status)return;if(S.currentStart)S.segments.push({status:S.status,start:S.currentStart,end:now()});S.status=s;S.currentStart=now();ev(s,src);save();render()}
function show(id,b){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('sel'));b?.classList.add('sel');if(id==='trip')setTimeout(initMap,100);if(id==='log')drawLog()}
document.querySelectorAll('nav [data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab,b));
document.querySelectorAll('[data-duty]').forEach(b=>b.onclick=()=>duty(b.dataset.duty));
$('startShift').onclick=()=>{S.shiftStart=S.shiftStart||now();if(S.status==='OFF DUTY')duty('ON DUTY');save();render()};
$('endShift').onclick=()=>{if(S.currentStart)S.segments.push({status:S.status,start:S.currentStart,end:now()});S.status='OFF DUTY';S.currentStart=now();S.shiftStart=null;ev('OFF DUTY','DRIVER','Shift ended');save();render()};
function render(){
 const d=active('DRIVING'),on=active('ON DUTY'),sl=active('SLEEPER'),off=active('OFF DUTY');
 const dr=Math.max(0,11*H-d),used=S.shiftStart?now()-S.shiftStart:Math.min(14*H,d+on),sh=Math.max(0,14*H-used),cy=S.cycleRemaining==null?null:Math.max(0,S.cycleRemaining*H-(d+on));
 [['driveLeft',fmt(dr)],['shiftLeft',fmt(sh)],['driveTot',fmt(d)],['driveTotal',fmt(d)],['onTot',fmt(on)],['onTotal',fmt(on)],['offTot',fmt(off)],['sleepTot',fmt(sl)],['cycleLeft',cy==null?'--':fmt(cy)],['current',S.status]].forEach(a=>$(a[0])&&($(a[0]).textContent=a[1]));
 if($('b11'))$('b11').style.width=Math.min(100,100*d/(11*H))+'%';if($('b14'))$('b14').style.width=Math.min(100,100*used/(14*H))+'%';
 document.querySelectorAll('[data-duty]').forEach(b=>b.classList.toggle('active',b.dataset.duty===S.status));
 let w=[];if(dr<1800000)w.push('Driving time is under 30 minutes.');if(sh<1800000)w.push('14-hour window is under 30 minutes.');
 if($('legal')){$('legal').className='status '+(w.length?'warn':'good');$('legal').textContent=w.length?'⚠️ '+w.join(' '):'🟢 Within prototype HOS clocks.'}
 if($('break')){$('break').className='status '+(d>8*H?'warn':'neutral');$('break').textContent=d>8*H?'⚠️ 30-minute break attention required':'No warning';}
 renderRadius();renderEvents();renderRecords();renderDocs();drawMap();drawRadiusMap();updateCompanion();
}
function renderRadius(){let m=S.base&&S.pos?air(S.base.lat,S.base.lon,S.pos.lat,S.pos.lon):null;if($('miles'))$('miles').textContent=m==null?'--':m.toFixed(1);if($('radius')){$('radius').textContent=m==null?'GPS / reporting location needed':m<=150?'🟢 INSIDE 150 AIR MILES':'🔴 OUTSIDE 150 AIR MILES';$('radius').className='status '+(m==null?'neutral':m<=150?'good':'bad')}if($('elig')){$('elig').className='status '+(m==null?'warn':m<=150?'good':'bad');$('elig').textContent=m==null?(S.base?'Enable GPS for live radius distance.':'Set your normal reporting location in Settings.'): `📍 ${m.toFixed(1)} / 150 air miles • ${m<=150?'INSIDE':'OUTSIDE'}`}let rc=$('radiusCommand');if(rc)rc.innerHTML=m==null?'<b>📍 150-AIR-MILE RADIUS</b><br><span class="muted">Set reporting location and enable GPS for live distance.</span>':`<b>📍 150-AIR-MILE RADIUS</b><br><strong style="font-size:28px">${m.toFixed(1)} / 150.0</strong> air miles<br><span class="${m<=150?'good':'bad'}">${m<=150?'🟢 INSIDE RADIUS':'🔴 OUTSIDE RADIUS'}</span>`}
function addRadiusUI(){if($('radiusCommand')||!$('home'))return;let c=document.createElement('div');c.className='card';c.innerHTML='<h2>📍 Radius Command Center</h2><div id="radiusCommand" class="status blue">Loading radius…</div><div id="radiusMap" style="height:280px;border-radius:12px;overflow:hidden"></div><p class="muted">Straight-line air-mile measurement from your normal reporting location. Distance display is not a legal exemption determination.</p>'; $('home').appendChild(c)}
function addUltimateUI(){if($('ultimatePanel'))return;let c=document.createElement('div');c.id='ultimatePanel';c.className='card';c.innerHTML=`<h2>🚛 Ultimate Driver Command Center</h2><div class="grid g4"><div><label>Truck</label><strong id="ucTruck">--</strong></div><div><label>Radius</label><strong id="ucRadius">--</strong></div><div><label>Fuel range</label><strong id="ucFuel">--</strong></div><div><label>Trip</label><strong id="ucTrip">--</strong></div></div><div id="morningBrief" class="status neutral">Your day-at-a-glance will appear here.</div><div class="row"><button data-q="parking">🅿️ FIND PARKING</button><button data-q="fuel">⛽ FIND FUEL</button><button data-q="weather">🌦️ WEATHER</button><button data-q="emergency">🆘 EMERGENCY</button></div>`;$('home').appendChild(c);c.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>quick(b.dataset.q))}
function updateCompanion(){if(!$('ultimatePanel'))return;let p=S.profile; if($('ucTruck'))$('ucTruck').textContent=p.unit||'Not set';let m=S.base&&S.pos?air(S.base.lat,S.base.lon,S.pos.lat,S.pos.lon):null;if($('ucRadius'))$('ucRadius').textContent=m==null?'--':m.toFixed(1)+' air mi';let mpg=7,fuel=0;if(S.fuel.length){let last=S.fuel[0];mpg=parseFloat(last.mpg)||7;fuel=parseFloat(last.gallons)||0}if($('ucFuel'))$('ucFuel').textContent=fuel?Math.round(fuel*mpg)+' mi est.':'Set fuel';if($('ucTrip'))$('ucTrip').textContent=S.routeMiles?Math.round(S.routeMiles)+' mi':'No trip';let b=[];if(p.driver)b.push('👋 '+p.driver);if(S.routeEnd)b.push('🎯 '+S.routeEnd);if(m!=null)b.push(m<=150?'🟢 Inside 150 air miles':'🔴 Outside 150 air miles');if(S.status==='DRIVING')b.push('🚛 Driving now');$('morningBrief').innerHTML=b.length?'<b>DRIVER BRIEF</b><br>'+b.join(' • '):'Set your driver/truck profile and trip to build your driver brief.'}
function hideGate(){if($('gpsGate'))$('gpsGate').style.display='none'}function gate(msg,bad=true){if(!$('gpsGate'))return;$('gpsGate').style.display='flex';if($('gpsMsg')){$('gpsMsg').className='status '+(bad?'bad':'warn');$('gpsMsg').textContent=msg}}
function startGPS(){if(!window.isSecureContext)return gate('Open the HTTPS GitHub Pages address for GPS.');if(!navigator.geolocation)return gate('This browser does not provide GPS. You can continue without GPS.');if($('gpsMsg'))$('gpsMsg').textContent='Requesting location permission…';navigator.geolocation.getCurrentPosition(p=>{S.pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed||0,accuracy:p.coords.accuracy||0};hideGate();ev(S.status,'GPS','GPS acquired');save();watchGPS();render()},e=>gate(e.code===1?'Location permission was denied. Enable it in iPhone Settings and retry.':e.code===2?'Location is unavailable. You can continue without GPS and retry later.':'GPS timed out. You can continue without GPS and retry.'),{enableHighAccuracy:true,maximumAge:10000,timeout:10000})}
function watchGPS(){if(!navigator.geolocation)return;if(watch!==null)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(p=>{S.pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed||0,accuracy:p.coords.accuracy||0};let mph=Math.max(0,(p.coords.speed||0)*2.236936);if($('speed'))$('speed').textContent=mph.toFixed(0)+' MPH';if(mph>=5){stopSince=null;if($('motion')){$('motion').className='status good';$('motion').textContent='🚛 MOVING — GPS active'}if(S.status!=='DRIVING')duty('DRIVING','GPS')}else{if($('motion')){$('motion').className='status blue';$('motion').textContent='⏸️ STOPPED — 5-minute timer running'}if(!stopSince)stopSince=now();if(S.status==='DRIVING'&&now()-stopSince>=FIVE&&S.autoMode!=='off'&&!S._stopPrompted){S._stopPrompted=true;ev(S.status,'GPS','Stopped 5 minutes');if(confirm('Stopped for 5 minutes. Record ON DUTY NOT DRIVING?'))duty('ON DUTY','AUTO-STOP');stopSince=null}if(mph>=1)S._stopPrompted=false}save();render()},()=>{if($('motion')){$('motion').className='status warn';$('motion').textContent='📡 GPS signal lost — app remains usable'}},{enableHighAccuracy:true,maximumAge:3000,timeout:10000})}
$('enableGps').onclick=startGPS;$('gpsHelp').onclick=()=>alert('iPhone: Settings → Privacy & Security → Location Services → ON → your browser → While Using. If opened inside another app, open the GitHub Pages address directly in Safari.');
if($('gpsGate')){let b=document.createElement('button');b.textContent='CONTINUE WITHOUT GPS';b.className='secondary';b.style.marginTop='8px';b.onclick=hideGate;$('gpsGate').querySelector('.gatebox')?.insertBefore(b,$('gpsHelp'))}
async function geo(q){let r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q)),a=await r.json();if(!a.length)throw Error('not found');return[+a[0].lon,+a[0].lat,a[0].display_name]}
$('saveBase').onclick=async()=>{try{let q=$('base').value.trim();if(!q)return;let p=await geo(q);S.base={lon:p[0],lat:p[1],name:p[2]};ev(S.status,'DRIVER','Reporting location saved');save();render();alert('Normal reporting location saved.')}catch(e){alert('Location not found. Try city/state or ZIP.')}};
$('gpsBase').onclick=()=>{if(!S.pos)return alert('Enable GPS first.');S.base={lat:S.pos.lat,lon:S.pos.lon,name:'Current GPS location'};ev(S.status,'DRIVER','Reporting location set from GPS');save();render();$('baseMsg').textContent='Saved: Current GPS location'};
function initMap(){if(map||!window.L||!$('map'))return;map=L.map('map').setView(S.pos?[S.pos.lat,S.pos.lon]:[39,-96],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);drawMap()}
function drawMap(){if(!map)return;if(S.pos){if(!me)me=L.marker([S.pos.lat,S.pos.lon]).addTo(map);else me.setLatLng([S.pos.lat,S.pos.lon])}if(S.base){if(!circle)circle=L.circle([S.base.lat,S.base.lon],{radius:241402,fill:false,color:'#2ea8ff'}).addTo(map);else circle.setLatLng([S.base.lat,S.base.lon])}if(S.route&&!line){line=L.geoJSON({type:'LineString',coordinates:S.route}).addTo(map)}}
function drawRadiusMap(){if(!window.L||!$('radiusMap'))return;if(!rmap){rmap=L.map('radiusMap').setView(S.pos?[S.pos.lat,S.pos.lon]:S.base?[S.base.lat,S.base.lon]:[39,-96],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(rmap)}if(S.pos){if(!rme)rme=L.marker([S.pos.lat,S.pos.lon]).addTo(rmap);else rme.setLatLng([S.pos.lat,S.pos.lon])}if(S.base){if(!rcircle)rcircle=L.circle([S.base.lat,S.base.lon],{radius:241402,fill:false,color:'#2ea8ff'}).addTo(rmap);else rcircle.setLatLng([S.base.lat,S.base.lon]);rmap.setView([S.base.lat,S.base.lon],7)}rmap.invalidateSize()}
$('planTrip').onclick=async()=>{try{let q=$('destination').value.trim();if(!q)return alert('Enter a destination.');let st=S.pos?[S.pos.lon,S.pos.lat]:(await geo($('start').value||'Portland, ME')).slice(0,2),en=(await geo(q)).slice(0,2),j=await(await fetch(`https://router.project-osrm.org/route/v1/driving/${st[0]},${st[1]};${en[0]},${en[1]}?overview=full&geometries=geojson`)).json();if(!j.routes?.length)throw Error();S.route=j.routes[0].geometry.coordinates;S.routeStart=S.pos?'Current GPS':$('start').value;S.routeEnd=q;S.routeMiles=j.routes[0].distance/1609.344;S.routeMinutes=j.routes[0].duration/60000;save();initMap();if(line)line.remove();line=L.geoJSON(j.routes[0].geometry).addTo(map);map.fitBounds(line.getBounds());let mi=S.routeMiles,m=Math.round(S.routeMinutes);$('tripMiles').textContent=mi.toFixed(0)+' mi';$('eta').textContent=Math.floor(m/60)+'h '+m%60+'m';$('tripSummary').className='status good';$('tripSummary').textContent='Route ready • '+mi.toFixed(0)+' miles • '+Math.floor(m/60)+'h '+m%60+'m';weather(en[1],en[0],'routeWeather');updateCompanion()}catch(e){$('tripSummary').className='status bad';$('tripSummary').textContent='Route unavailable. Try another destination.'}};
async function weather(lat,lon,target){try{let j=await(await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`)).json(),rain=j.daily.precipitation_probability_max[0]||0;if(target==='routeWeather'){$(target).innerHTML=`Destination: <b>${j.current.temperature_2m}°</b> • Wind ${j.current.wind_speed_10m} • Rain ${rain}%`;$('routeRisk').className='status '+(rain>=60?'warn':'good');$('routeRisk').textContent=rain>=60?'⚠️ Wet-weather signal':'🟢 Lower precipitation signal'}else{$(target).className='status blue';$(target).innerHTML=`Current: <b>${j.current.temperature_2m}°</b> • Wind ${j.current.wind_speed_10m} • Rain ${rain}%`;$('forecast').innerHTML=j.daily.time.slice(0,7).map((d,i)=>`<div class="card"><b>${d}</b><br><strong>${Math.round(j.daily.temperature_2m_max[i])}°</strong><br><span class="muted">Low ${Math.round(j.daily.temperature_2m_min[i])}° • Rain ${j.daily.precipitation_probability_max[i]}%</span></div>`).join('')}}catch(e){$(target).textContent='Weather service unavailable.'}}
$('getWeather').onclick=async()=>{try{let p=await geo($('weatherPlace').value);weather(p[1],p[0],'weatherNow')}catch(e){$('weatherNow').textContent='Location not found.'}};$('weatherHere').onclick=()=>S.pos?weather(S.pos.lat,S.pos.lon,'weatherNow'):alert('Enable GPS first.');
document.querySelectorAll('[data-poi]').forEach(b=>b.onclick=async()=>{if(!S.pos)return alert('Enable GPS first.');let amen=b.dataset.poi==='fuel'?'fuel':b.dataset.poi==='parking'?'parking':'truck_repair';try{let u='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(`[out:json];nwr[amenity=${amen}](around:30000,${S.pos.lat},${S.pos.lon});out center 10;`),j=await(await fetch(u)).json();$('poi').innerHTML=j.elements.map(x=>`<div class="status neutral"><b>${x.tags?.name||b.dataset.poi}</b><br><span class="muted">Nearby result</span></div>`).join('')||'No nearby results.'}catch(e){$('poi').textContent='Nearby service unavailable.'}});
function renderEvents(){$('events').innerHTML=(S.events||[]).slice(0,100).map(e=>`<tr><td>${new Date(e.time).toLocaleString()}</td><td>${e.status}</td><td>${e.loc||''}</td><td>${e.source||''}</td><td>${e.note||''}</td></tr>`).join('')}
function drawLog(){let g=$('logGrid');if(!g)return;g.innerHTML='';for(let h=0;h<24;h++){let d=document.createElement('div');d.className='hour';d.innerHTML='<div class="lane l0"></div><div class="lane l1"></div><div class="lane l2"></div><div class="lane l3"></div><span>'+h+'</span>';g.appendChild(d)}}
const items=['Brakes','Tires / wheels','Lights / reflectors','Steering','Suspension','Coupling','Mirrors','Emergency equipment','Windshield / wipers','Fluids / leaks'];
function checks(t){let e=$(t);if(e)e.innerHTML=items.map((x,i)=>`<label class="check"><input type="checkbox" data-${t}="${i}">${x}</label>`).join('')};checks('pre');checks('post');
document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{let t=b.dataset.complete;S.inspect[t]={time:new Date().toISOString(),items:[...document.querySelectorAll(`[data-${t}]`)].map(x=>x.checked)};save();$(t+'Msg').className='status good';$(t+'Msg').textContent='Completed '+new Date().toLocaleString()});document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{let t=b.dataset.clear;S.inspect[t]={};document.querySelectorAll(`[data-${t}]`).forEach(x=>x.checked=false);save();$(t+'Msg').textContent='Not completed.'});
$('saveDefect').onclick=()=>{let v=$('defect').value.trim();S.records.unshift({date:new Date().toLocaleDateString(),in:'',out:'',hours:'',note:'DEFECT: '+v});save();$('defectMsg').className='status '+(v?'warn':'neutral');$('defectMsg').textContent=v?'Defect saved locally.':'No defect saved.';renderRecords()};
$('saveRecord').onclick=()=>{S.records.unshift({date:$('rdate').value||new Date().toLocaleDateString(),in:$('rin').value,out:$('rout').value,hours:$('rhrs').value,note:$('rnote').value});save();renderRecords()};function renderRecords(){$('records').innerHTML=(S.records||[]).map(r=>`<tr><td>${r.date}</td><td>${r.in}</td><td>${r.out}</td><td>${r.hours}</td><td>${r.note}</td></tr>`).join('')}
$('addDoc').onclick=()=>{if(!$('docName').value||!$('docDate').value)return;S.docs.push({name:$('docName').value,date:$('docDate').value,note:$('docNote').value});save();renderDocs()};function renderDocs(){$('docs').innerHTML=(S.docs||[]).map(d=>`<div class="status ${new Date(d.date+'T23:59:59')<new Date()?'bad':'neutral'}">📄 ${d.name} — ${d.date}<br><span class="muted">${d.note||''}</span></div>`).join('')}
// Settings are rendered only on startup/save, never every second. This prevents fields from being overwritten while typing.
function loadSettingsFields(){let p=S.profile;['driver','carrier','dot','unit','vin','trailer'].forEach(k=>$(k)&&($(k).value=p[k]||''));if($('cycleType'))$('cycleType').value=S.cycle||60;if($('cycleStart'))$('cycleStart').value=S.cycleRemaining??'';if($('baseMsg'))$('baseMsg').textContent=S.base?'Saved: '+S.base.name:'Not set.'}
$('saveSettings').onclick=()=>{let p={};['driver','carrier','dot','unit','vin','trailer'].forEach(k=>p[k]=$(k).value.trim());S.profile=p;save();loadSettingsFields();updateCompanion();alert('Driver / truck profile saved.')};
$('saveHOS').onclick=()=>{S.cycle=+$('cycleType').value;let v=parseFloat($('cycleStart').value);S.cycleRemaining=Number.isFinite(v)?v:null;save();render();alert('HOS settings saved.')};$('reset').onclick=()=>{if(confirm('Reset today\'s prototype HOS data?')){S.segments=[];S.events=[];S.status='OFF DUTY';S.currentStart=now();S.shiftStart=null;save();render()}};
$('certify').onclick=()=>{$('cert').className='status good';$('cert').textContent='Prototype log certified locally at '+new Date().toLocaleString()};
$('printLog').onclick=()=>window.print();$('export').onclick=()=>{let rows=[['Time','Status','Location','Source','Note'],...S.events.map(e=>[e.time,e.status,e.loc,e.source,e.note])],csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='hos150-events.csv';a.click()};
function addTools(){let t=$('tools');if(!t||$('companionTools'))return;let c=document.createElement('div');c.id='companionTools';c.className='card';c.innerHTML='<h2>🧰 Complete Driver Companion</h2><div class="grid g3"><button data-comp="fuel">⛽ Fuel</button><button data-comp="expense">💰 Expense</button><button data-comp="maintenance">🔧 Maintenance</button><button data-comp="emergency">🆘 Emergency</button><button data-comp="load">📦 Load / BOL</button><button data-comp="pod">✍️ POD</button></div><div id="companionPanel" class="status neutral">Choose a tool.</div>';t.appendChild(c);document.querySelectorAll('[data-comp]').forEach(b=>b.onclick=()=>{let x=b.dataset.comp,p=$('companionPanel');if(x==='emergency')p.innerHTML='<b>🆘 EMERGENCY MODE</b><br>GPS: '+(S.pos?`${S.pos.lat.toFixed(5)}, ${S.pos.lon.toFixed(5)}`:'unavailable')+'<br><button onclick="location.href=\'tel:911\'">CALL 911</button>';else if(x==='fuel')p.innerHTML='<b>⛽ Fuel</b><br><div class="row"><input id="fuelGall" placeholder="Gallons"><input id="fuelPrice" placeholder="Price / gallon"><input id="fuelOdo" placeholder="Odometer"><input id="fuelMpg" placeholder="MPG"></div><button onclick="hosQuick(\'fuel\')">SAVE FUEL</button>';else if(x==='expense')p.innerHTML='<b>💰 Expense</b><br><div class="row"><input id="expType" placeholder="Expense type"><input id="expAmt" placeholder="Amount"></div><button onclick="hosQuick(\'expense\')">SAVE EXPENSE</button>';else if(x==='maintenance')p.innerHTML='<b>🔧 Maintenance</b><br><textarea id="maint" placeholder="Service / mileage / repair note"></textarea><button onclick="hosQuick(\'maintenance\')">SAVE NOTE</button>';else if(x==='load')p.innerHTML='<b>📦 Load / BOL</b><br><div class="row"><input id="loadNo" placeholder="Load / BOL #"><input id="shipper" placeholder="Shipper"><input id="receiver" placeholder="Receiver"></div><textarea id="loadNote" placeholder="Weight / pieces / appointment / notes"></textarea><button onclick="hosQuick(\'load\')">SAVE LOAD</button>';else p.innerHTML='<b>✍️ POD</b><br><textarea id="podNote" placeholder="Delivery notes / customer name"></textarea><button onclick="hosQuick(\'pod\')">SAVE POD NOTE</button>'})}
window.hosQuick=t=>{let d={type:t,time:new Date().toISOString()};document.querySelectorAll('#companionPanel input,#companionPanel textarea').forEach(e=>d[e.id]=e.value);if(t==='fuel')S.fuel.unshift(d);else if(t==='expense')S.expenses.unshift(d);else if(t==='maintenance')S.maintenance.unshift(d);else if(t==='load')S.loads.unshift(d);else if(t==='pod')S.pod.unshift(d);S.records.unshift({date:new Date().toLocaleDateString(),in:'',out:'',hours:'',note:JSON.stringify(d)});save();renderRecords();updateCompanion();$('companionPanel').innerHTML='<span class="good">Saved locally.</span>'};
function quick(t){show('tools',document.querySelector('nav [data-tab="tools"]'));let b=document.querySelector(`[data-comp="${t==='fuel'?'fuel':t==='parking'?'fuel':t==='emergency'?'emergency':'weather'}"]`);if(b)b.click();if(t==='weather')show('weather',document.querySelector('nav [data-tab="weather"]'))}
addRadiusUI();addUltimateUI();addTools();loadSettingsFields();if(S.pos)watchGPS();else if($('gpsGate'))$('gpsGate').style.display='flex';render();setInterval(render,1000);
})();