(()=>{
'use strict';
const KEY='hos150v13'; const H=3600000, FIVE=300000;
const $=id=>document.getElementById(id), now=()=>Date.now();
const fresh={status:'OFF DUTY',currentStart:now(),segments:[],events:[],pos:null,base:null,cycle:60,cycleRemaining:null,shiftStart:null,records:[],docs:[],inspect:{pre:{},post:{}},route:null,routeStart:null,routeEnd:null,routeMiles:null,routeMinutes:null,profile:{driver:'',carrier:'',dot:'',unit:'',vin:'',trailer:'',height:'',weight:'',axles:'',tanks:'',mpg:'7',fuelPct:'',minFuel:'20'},fuel:[],expenses:[],maintenance:[],loads:[],pod:[],tripPlan:null};
let S=Object.assign({},fresh,JSON.parse(localStorage.getItem(KEY)||'{}')); S.profile=Object.assign({},fresh.profile,S.profile||{}); S.segments=S.segments||[]; S.events=S.events||[]; S.fuel=S.fuel||[]; S.expenses=S.expenses||[]; S.maintenance=S.maintenance||[]; S.loads=S.loads||[];
let watch=null,stopSince=null,map=null,me=null,circle=null,line=null,rmap=null,rme=null,rcircle=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(S)); const fmt=x=>{x=Math.max(0,x||0);let m=Math.floor(x/60000);return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')};
const active=s=>(S.segments||[]).reduce((n,x)=>n+(x.status===s?Math.max(0,x.end-x.start):0),0)+(S.status===s?Math.max(0,now()-S.currentStart):0);
const air=(a,b,c,d)=>{const R=3958.761,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
function ev(status,source='DRIVER',note='Duty status change'){S.events.unshift({time:new Date().toISOString(),status,source,note,loc:S.pos?`${S.pos.lat.toFixed(5)},${S.pos.lon.toFixed(5)}`:'GPS unavailable'});S.events=S.events.slice(0,1000)}
function duty(s,src='DRIVER'){if(s===S.status)return;if(S.currentStart)S.segments.push({status:S.status,start:S.currentStart,end:now()});S.status=s;S.currentStart=now();ev(s,src);save();render()}
function show(id,b){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('sel'));b?.classList.add('sel');if(id==='trip')setTimeout(initMap,100);if(id==='log')drawLog()}
document.querySelectorAll('nav [data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab,b)); document.querySelectorAll('[data-duty]').forEach(b=>b.onclick=()=>duty(b.dataset.duty));
$('startShift')?.addEventListener('click',()=>{S.shiftStart=S.shiftStart||now();if(S.status==='OFF DUTY')duty('ON DUTY');save();render()}); $('endShift')?.addEventListener('click',()=>{if(S.currentStart)S.segments.push({status:S.status,start:S.currentStart,end:now()});S.status='OFF DUTY';S.currentStart=now();S.shiftStart=null;ev('OFF DUTY','DRIVER','Shift ended');save();render()});
function render(){const d=active('DRIVING'),on=active('ON DUTY'),sl=active('SLEEPER'),off=active('OFF DUTY');let dr=Math.max(0,11*H-d),used=S.shiftStart?now()-S.shiftStart:Math.min(14*H,d+on),sh=Math.max(0,14*H-used),cy=S.cycleRemaining==null?null:Math.max(0,S.cycleRemaining*H-(d+on));[['driveLeft',fmt(dr)],['shiftLeft',fmt(sh)],['driveTot',fmt(d)],['driveTotal',fmt(d)],['onTot',fmt(on)],['onTotal',fmt(on)],['offTot',fmt(off)],['sleepTot',fmt(sl)],['cycleLeft',cy==null?'--':fmt(cy)],['current',S.status]].forEach(a=>$(a[0])&&($(a[0]).textContent=a[1]));if($('b11'))$('b11').style.width=Math.min(100,100*d/(11*H))+'%';if($('b14'))$('b14').style.width=Math.min(100,100*used/(14*H))+'%';document.querySelectorAll('[data-duty]').forEach(b=>b.classList.toggle('active',b.dataset.duty===S.status));let w=[];if(dr<1800000)w.push('Driving time is under 30 minutes.');if(sh<1800000)w.push('14-hour window is under 30 minutes.');if($('legal')){$('legal').className='status '+(w.length?'warn':'good');$('legal').textContent=w.length?'⚠️ '+w.join(' '):'🟢 Within prototype HOS clocks.'}if($('break')){$('break').className='status '+(d>8*H?'warn':'neutral');$('break').textContent=d>8*H?'⚠️ 30-minute break attention required':'No warning'}renderRadius();renderEvents();renderRecords();renderDocs();drawMap();drawRadiusMap();commandCenter();}
function renderRadius(){let m=S.base&&S.pos?air(S.base.lat,S.base.lon,S.pos.lat,S.pos.lon):null;if($('miles'))$('miles').textContent=m==null?'--':m.toFixed(1);if($('radius')){$('radius').textContent=m==null?'GPS / reporting location needed':m<=150?'🟢 INSIDE 150 AIR MILES':'🔴 OUTSIDE 150 AIR MILES';$('radius').className='status '+(m==null?'neutral':m<=150?'good':'bad')}if($('elig')){$('elig').className='status '+(m==null?'warn':m<=150?'good':'bad');$('elig').textContent=m==null?(S.base?'Enable GPS for live radius distance.':'Set your normal reporting location in Settings.'): `📍 ${m.toFixed(1)} / 150 air miles • ${m<=150?'INSIDE':'OUTSIDE'}`}}
function commandCenter(){let el=$('ultimatePanel');if(!el&&$('home')){el=document.createElement('div');el.id='ultimatePanel';el.className='card';el.innerHTML='<h2>🚛 Ultimate Driver Command Center</h2><div class="grid g4"><div><label>Truck</label><strong id="ucTruck">--</strong></div><div><label>Fuel range</label><strong id="ucFuel">--</strong></div><div><label>Trip ETA</label><strong id="ucEta">--</strong></div><div><label>Radius</label><strong id="ucRadius">--</strong></div></div><div id="morningBrief" class="status neutral">Set your truck, fuel and destination for a live brief.</div><div class="row"><button data-cmd="plan">🧭 PLAN MY DAY</button><button data-cmd="parking">🅿️ PARKING</button><button data-cmd="fuel">⛽ FUEL</button><button data-cmd="weather">🌦️ WEATHER</button><button data-cmd="emergency">🆘 EMERGENCY</button></div>'; $('home').appendChild(el);el.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>quick(b.dataset.cmd))}let p=S.profile,mpg=parseFloat(p.mpg)||7,tank=parseFloat(p.tanks)||0,pct=parseFloat(p.fuelPct)||0,range=tank&&pct?Math.round(tank*pct/100*mpg):null,m=S.base&&S.pos?air(S.base.lat,S.base.lon,S.pos.lat,S.pos.lon):null;if($('ucTruck'))$('ucTruck').textContent=p.unit||'Not set';if($('ucFuel'))$('ucFuel').textContent=range?range+' mi':'Set tank/MPG/fuel';if($('ucEta'))$('ucEta').textContent=S.routeMiles?etaText(): '--';if($('ucRadius'))$('ucRadius').textContent=m==null?'--':m.toFixed(1)+' air mi';if($('morningBrief'))$('morningBrief').innerHTML=briefText()}
function etaText(){let mins=Number(S.routeMinutes)||0,driveLeft=Math.max(0,11*H-active('DRIVING'))/60000;let extra=mins>driveLeft?30:0;let d=new Date(Date.now()+(mins+extra)*60000);return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function briefText(){let a=[];if(S.profile.driver)a.push('👋 '+S.profile.driver);if(S.routeEnd)a.push('🎯 '+S.routeEnd);if(S.routeMiles)a.push('🧭 '+Math.round(S.routeMiles)+' road miles');if(S.routeMiles)a.push('⏱️ ETA '+etaText());let p=S.profile,range=(parseFloat(p.tanks)||0)*(parseFloat(p.fuelPct)||0)/100*(parseFloat(p.mpg)||7);if(range)a.push('⛽ range '+Math.round(range)+' mi');let m=S.base&&S.pos?air(S.base.lat,S.base.lon,S.pos.lat,S.pos.lon):null;if(m!=null)a.push(m<=150?'🟢 150-air-mile radius':'🔴 outside radius');return '<b>DRIVER BRIEF</b><br>'+(a.length?a.join(' • '):'Set your driver/truck profile and destination.')}
function gate(msg){if(!$('gpsGate'))return;$('gpsGate').style.display='flex';if($('gpsMsg')){$('gpsMsg').className='status warn';$('gpsMsg').textContent=msg}}
function hideGate(){$('gpsGate')&&($('gpsGate').style.display='none')}
function startGPS(){if(!window.isSecureContext)return gate('Open the HTTPS GitHub Pages address for GPS.');if(!navigator.geolocation)return gate('GPS unavailable. You can continue without GPS.');if($('gpsMsg'))$('gpsMsg').textContent='Requesting location permission…';navigator.geolocation.getCurrentPosition(p=>{S.pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed||0,accuracy:p.coords.accuracy||0};hideGate();ev(S.status,'GPS','GPS acquired');save();watchGPS();render()},e=>gate(e.code===1?'Location permission denied. Enable Location Services in iPhone Settings.':e.code===2?'Location unavailable. You can continue without GPS.':'GPS timed out. You can continue without GPS.'),{enableHighAccuracy:true,maximumAge:10000,timeout:10000})}
function watchGPS(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(p=>{S.pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed||0,accuracy:p.coords.accuracy||0};let mph=Math.max(0,(p.coords.speed||0)*2.236936);if($('speed'))$('speed').textContent=mph.toFixed(0)+' MPH';if(mph>=5){stopSince=null;if($('motion')){$('motion').className='status good';$('motion').textContent='🚛 MOVING — GPS active'}if(S.status!=='DRIVING')duty('DRIVING','GPS')}else{if($('motion')){$('motion').className='status blue';$('motion').textContent='⏸️ STOPPED — 5-minute timer running'}if(!stopSince)stopSince=now();if(S.status==='DRIVING'&&now()-stopSince>=FIVE&&!S._stopPrompted){S._stopPrompted=true;ev(S.status,'GPS','Stopped 5 minutes');if(confirm('Stopped for 5 minutes. Record ON DUTY NOT DRIVING?'))duty('ON DUTY','AUTO-STOP');stopSince=null}}save();render()},()=>{$('motion')&&($('motion').textContent='📡 GPS signal lost — app remains usable')},{enableHighAccuracy:true,maximumAge:3000,timeout:10000})}
$('enableGps')?.addEventListener('click',startGPS);$('gpsHelp')?.addEventListener('click',()=>alert('iPhone: Settings → Privacy & Security → Location Services → ON → your browser → While Using. If opened inside another app, open the GitHub Pages address directly in Safari.'));if($('gpsGate')){let b=document.createElement('button');b.textContent='CONTINUE WITHOUT GPS';b.className='secondary';b.onclick=hideGate;$('gpsGate').querySelector('.gatebox')?.insertBefore(b,$('gpsHelp'))}
async function geo(q){let r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q));let a=await r.json();if(!a.length)throw Error('not found');return[+a[0].lon,+a[0].lat,a[0].display_name]}
$('saveBase')?.addEventListener('click',async()=>{try{let q=$('base').value.trim();if(!q)return;let p=await geo(q);S.base={lon:p[0],lat:p[1],name:p[2]};ev(S.status,'DRIVER','Reporting location saved');save();render();$('baseMsg').textContent='Saved: '+p[2]}catch(e){alert('Location not found. Try city/state or ZIP.')}});$('gpsBase')?.addEventListener('click',()=>{if(!S.pos)return alert('Enable GPS first.');S.base={lat:S.pos.lat,lon:S.pos.lon,name:'Current GPS location'};save();render()});
function initMap(){if(map||!window.L||!$('map'))return;map=L.map('map').setView(S.pos?[S.pos.lat,S.pos.lon]:[39,-96],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);drawMap()};function drawMap(){if(!map)return;if(S.pos){if(!me)me=L.marker([S.pos.lat,S.pos.lon]).addTo(map);else me.setLatLng([S.pos.lat,S.pos.lon])}if(S.base){if(!circle)circle=L.circle([S.base.lat,S.base.lon],{radius:241402,fill:false}).addTo(map);else circle.setLatLng([S.base.lat,S.base.lon])}if(S.route){if(line)line.remove();line=L.geoJSON({type:'LineString',coordinates:S.route}).addTo(map)}}
function drawRadiusMap(){if(!window.L||!$('radiusMap'))return;if(!rmap){rmap=L.map('radiusMap').setView(S.base?[S.base.lat,S.base.lon]:[39,-96],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(rmap)}if(S.pos){if(!rme)rme=L.marker([S.pos.lat,S.pos.lon]).addTo(rmap);else rme.setLatLng([S.pos.lat,S.pos.lon])}if(S.base){if(!rcircle)rcircle=L.circle([S.base.lat,S.base.lon],{radius:241402,fill:false}).addTo(rmap);else rcircle.setLatLng([S.base.lat,S.base.lon])}rmap.invalidateSize()}
function addRadiusUI(){if($('radiusCommand')||!$('home'))return;let c=document.createElement('div');c.className='card';c.innerHTML='<h2>📍 150-Air-Mile Radius Command Center</h2><div id="radiusCommand" class="status neutral">Waiting for GPS/reporting location.</div><div id="radiusMap" style="height:280px;border-radius:12px;overflow:hidden"></div><p class="muted">Straight-line air-mile display. It does not determine legal exemption eligibility.</p>';$('home').appendChild(c)}
$('planTrip')?.addEventListener('click',async()=>{try{let q=$('destination').value.trim();if(!q)return alert('Enter a destination.');let st=S.pos?[S.pos.lon,S.pos.lat]:(await geo($('start').value||'Portland, ME')).slice(0,2),en=(await geo(q)).slice(0,2),j=await(await fetch(`https://router.project-osrm.org/route/v1/driving/${st[0]},${st[1]};${en[0]},${en[1]}?overview=full&geometries=geojson`)).json();if(!j.routes?.length)throw Error();let r=j.routes[0];S.route=r.geometry.coordinates;S.routeStart=S.pos?'Current GPS':$('start').value;S.routeEnd=q;S.routeMiles=r.distance/1609.344;S.routeMinutes=r.duration/60000;save();initMap();if(line)line.remove();line=L.geoJSON(r.geometry).addTo(map);map.fitBounds(line.getBounds());$('tripMiles').textContent=S.routeMiles.toFixed(0)+' mi';$('eta').textContent=etaText();$('tripSummary').className='status good';$('tripSummary').textContent='Route ready • '+S.routeMiles.toFixed(0)+' road miles • ETA '+etaText();weather(en[1],en[0],'routeWeather');render()}catch(e){$('tripSummary').className='status bad';$('tripSummary').textContent='Route unavailable. Try another destination.'}});
async function weather(lat,lon,target){try{let j=await(await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,precipitation,wind_speed_10m,weather_code&hourly=temperature_2m,precipitation_probability,wind_speed_10m,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`)).json();if(target==='routeWeather'){$(target).innerHTML=`Destination: ${j.current.temperature_2m}° • Wind ${j.current.wind_speed_10m} • Precip ${j.current.precipitation}`;return}$('weatherNow').innerHTML=`🌡️ ${j.current.temperature_2m}° • 💨 ${j.current.wind_speed_10m} • 🌧️ ${j.current.precipitation}`;if($('forecast'))$('forecast').innerHTML=j.daily.time.slice(0,7).map((d,i)=>`<div class="card"><b>${d}</b><br>${j.daily.temperature_2m_min[i]}° / ${j.daily.temperature_2m_max[i]}°<br>Rain ${j.daily.precipitation_probability_max[i]}%</div>`).join('')}catch(e){if($(target))$(target).textContent='Weather unavailable.'}}
$('getWeather')?.addEventListener('click',async()=>{try{let p=await geo($('weatherPlace').value);weather(p[1],p[0],'weather')}catch(e){$('weatherNow').textContent='Location not found.'}});$('weatherHere')?.addEventListener('click',()=>S.pos?weather(S.pos.lat,S.pos.lon,'weather'):alert('Enable GPS first.'));
function quick(q){if(q==='plan'){show('trip',document.querySelector('[data-tab="trip"]'));return}if(q==='weather'){show('weather',document.querySelector('[data-tab="weather"]'));return}if(q==='parking'||q==='fuel'){if(S.pos)window.open('https://www.google.com/maps/search/'+encodeURIComponent(q==='fuel'?'truck fuel':'truck parking')+'/@'+S.pos.lat+','+S.pos.lon+',11z','_blank');else alert('Enable GPS first.');return}if(q==='emergency'){let msg=`EMERGENCY LOCATION\n${S.pos?S.pos.lat+', '+S.pos.lon:'GPS unavailable'}\nTruck: ${S.profile.unit||'not set'}\nDriver: ${S.profile.driver||'not set'}`;alert(msg);if(S.pos)window.open(`https://www.google.com/maps/search/hospital/@${S.pos.lat},${S.pos.lon},11z`,'_blank')}}
function drawLog(){if(!$('logGrid'))return;let cells=[];for(let h=0;h<24;h++)cells.push(`<div><small>${String(h).padStart(2,'0')}</small><div class="logcell"></div></div>`);$('logGrid').innerHTML=cells.join('')}
function renderEvents(){if(!$('events'))return;$('events').innerHTML=(S.events||[]).slice(0,100).map(e=>`<tr><td>${new Date(e.time).toLocaleString()}</td><td>${e.status}</td><td>${e.loc}</td><td>${e.source}</td><td>${e.note}</td></tr>`).join('')}
function renderRecords(){if(!$('records'))return;$('records').innerHTML=(S.records||[]).map(r=>`<tr><td>${r.date}</td><td>${r.in||''}</td><td>${r.out||''}</td><td>${r.hrs||''}</td><td>${r.note||''}</td></tr>`).join('')}
function renderDocs(){if(!$('docs'))return;$('docs').innerHTML=(S.docs||[]).map(d=>`<div class="status neutral"><b>${d.name}</b> — ${d.date} ${d.note||''}</div>`).join('')}
$('saveSettings')?.addEventListener('click',()=>{['driver','carrier','dot','unit','vin','trailer','height','weight','axles','tanks','mpg','fuelPct','minFuel'].forEach(k=>{let e=$(k);if(e)S.profile[k]=e.value.trim()});save();render();alert('Driver and truck profile saved.')});$('saveHOS')?.addEventListener('click',()=>{S.cycle=+$('cycleType').value;S.cycleRemaining=parseFloat($('cycleStart').value)||S.cycle;save();render()});$('saveRecord')?.addEventListener('click',()=>{S.records.push({date:$('rdate').value,in:$('rin').value,out:$('rout').value,hrs:$('rhrs').value,note:$('rnote').value});save();render()});$('addDoc')?.addEventListener('click',()=>{S.docs.push({name:$('docName').value,date:$('docDate').value,note:$('docNote').value});save();render()});$('saveDefect')?.addEventListener('click',()=>{S.events.unshift({time:new Date().toISOString(),status:S.status,source:'INSPECTION',note:$('defect').value,loc:S.pos?`${S.pos.lat},${S.pos.lon}`:'GPS unavailable'});save();render();$('defectMsg').textContent='Defect saved.'});
document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{$(b.dataset.complete==='pre'?'preMsg':'postMsg').textContent='Completed '+new Date().toLocaleString();save()});$('printLog')?.addEventListener('click',()=>window.print());$('export')?.addEventListener('click',()=>{let rows=['time,status,location,source,note',...(S.events||[]).map(e=>[e.time,e.status,e.loc,e.source,e.note].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','))];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='driver-log.csv';a.click()});
addRadiusUI();commandCenter(); if(S.pos)watchGPS(); if(S.base&&$('base'))$('base').value=S.base.name||''; if(S.profile)Object.keys(S.profile).forEach(k=>$(k)&&($(k).value=S.profile[k]||''));setInterval(()=>{render()},1000);render();
})();