/* HOS 150 DRIVER OS V21 — navigation + truck intelligence + route intelligence
   Prototype: public/open data only. Not certified truck routing or ELD.
*/
(()=>{
'use strict';
const KEY='hos150v13';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
let s=load(), nav={map:null,route:null,steps:[],idx:0,watch:null,last:null,dest:null};
const q=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function css(){if(q('v21css'))return;let st=document.createElement('style');st.id='v21css';st.textContent=`
.v21bar{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.v21pill{padding:7px 10px;border-radius:999px;background:#111827;color:white;font-weight:700;font-size:12px}.v21next{font-size:20px;font-weight:800}.v21small{font-size:12px;color:#64748b}.v21warn{border-left:5px solid #dc2626;background:#fef2f2;padding:10px;border-radius:8px;margin:8px 0}.v21ok{border-left:5px solid #16a34a;background:#f0fdf4;padding:10px;border-radius:8px;margin:8px 0}.v21grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.v21list{display:grid;gap:7px}.v21item{padding:9px;border:1px solid #e2e8f0;border-radius:9px;background:#fff}.v21map{height:58vh;min-height:360px;border-radius:12px;overflow:hidden}.v21sticky{position:sticky;top:0;z-index:500;background:rgba(255,255,255,.96);padding:8px;border-bottom:1px solid #ddd}.v21turn{font-size:14px;font-weight:700}.v21exit{font-size:12px;color:#475569}.v21danger{color:#b91c1c;font-weight:800}.v21routebtn{font-size:16px;font-weight:800;padding:12px}.v21modal{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9999;display:flex;align-items:flex-end}.v21sheet{background:white;width:100%;max-height:85vh;overflow:auto;border-radius:18px 18px 0 0;padding:16px}.v21sheet h2{margin-top:0}
@media(max-width:600px){.v21map{height:55vh}.v21grid{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(st)}
function install(){css();let b=[...document.querySelectorAll('[data-tab="route"]')][0];if(b)b.textContent='🧭 GPS NAVIGATOR';renderRoute();document.addEventListener('click',e=>{if(e.target.id==='v21Go')go();if(e.target.id==='v21Recenter'&&nav.last&&nav.map)nav.map.setView([nav.last.lat,nav.last.lon],15);if(e.target.id==='v21Truck')truckSheet();if(e.target.id==='v21Intel')intelSheet();if(e.target.id==='v21Fuel')findPOI('fuel');if(e.target.id==='v21Park')findPOI('parking');if(e.target.id==='v21Rest')findPOI('rest');if(e.target.id==='v21Repair')findPOI('repair');if(e.target.id==='v21Scale')findPOI('weigh_station');});setTimeout(startGPS,300)}
function renderRoute(){let r=q('route');if(!r)return;r.innerHTML=`<div class="v21sticky"><div class="v21bar"><input id="v21Dest" placeholder="Where to? Address, city, ZIP" style="flex:1;min-width:150px"><button id="v21Go" class="v21routebtn">GO</button><button id="v21Recenter">◎</button></div><div class="v21bar"><span class="v21pill" id="v21Speed">-- MPH</span><span class="v21pill" id="v21HOS">HOS --</span><span class="v21pill" id="v21Radius">150 AIR --</span></div></div><div id="v21Map" class="v21map"></div><div class="card"><div id="v21Next" class="v21next">Enter a destination</div><div id="v21Road" class="v21small">Turn-by-turn navigation will appear here.</div><div class="v21grid"><div><label>ETA</label><strong id="v21Eta">--</strong></div><div><label>Distance</label><strong id="v21Miles">--</strong></div><div><label>HOS-aware ETA</label><strong id="v21HosEta">--</strong></div><div><label>Arrival</label><strong id="v21Arrival">--</strong></div></div></div><div class="v21bar"><button id="v21Truck">🚛 Truck Profile</button><button id="v21Intel">⚠️ Route Intel</button><button id="v21Fuel">⛽ Fuel</button><button id="v21Park">🅿️ Parking</button><button id="v21Rest">🛏️ Rest</button><button id="v21Repair">🔧 Repair</button><button id="v21Scale">⚖️ Scale</button></div><div id="v21Alerts"></div><div class="card"><h3>Navigation notes</h3><div class="v21small">Routing uses public road data and is not certified truck routing. Posted signs, bridge clearances, weight limits, hazmat restrictions and local rules always control.</div></div>`;setTimeout(initMap,50)}
function initMap(){if(!window.L||nav.map||!q('v21Map'))return;nav.map=L.map('v21Map',{zoomControl:false}).setView([39.5,-98.35],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(nav.map)}
function startGPS(){if(!navigator.geolocation)return;nav.watch=navigator.geolocation.watchPosition(p=>{nav.last={lat:p.coords.latitude,lon:p.coords.longitude,speed:(p.coords.speed||0)*2.23694,heading:p.coords.heading};if(q('v21Speed'))q('v21Speed').textContent=Math.round(nav.last.speed)+' MPH';if(nav.map&&nav.map.getZoom()<8)nav.map.setView([nav.last.lat,nav.last.lon],15);updateRadius();updateNav();},()=>{}, {enableHighAccuracy:true,maximumAge:2000,timeout:10000})}
function updateRadius(){let st=load();if(!nav.last){return}let base=st.baseCoords;if(base){let d=dist(nav.last.lat,nav.last.lon,base.lat,base.lon);q('v21Radius').textContent=`150 AIR ${d<=277.8?'IN':'OUT'} • ${d.toFixed(1)} km`;}}
function dist(a,b,c,d){let R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
async function geocode(x){let u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+encodeURIComponent(x);let a=await fetch(u,{headers:{Accept:'application/json'}}).then(r=>r.json());if(!a[0])throw Error('Destination not found');return {lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name}}
async function go(){let x=q('v21Dest').value.trim();if(!x)return alert('Enter a destination.');try{q('v21Next').textContent='Finding route…';let d=await geocode(x);nav.dest=d;let o=nav.last?`${nav.last.lon},${nav.last.lat}`:null;if(!o)return alert('Allow GPS or use a destination from the map.');let u=`https://router.project-osrm.org/route/v1/driving/${o};${d.lon},${d.lat}?overview=full&geometries=geojson&steps=true`;let data=await fetch(u).then(r=>r.json());if(data.code!=='Ok')throw Error('Route unavailable');nav.route=data.routes[0];nav.steps=nav.route.legs.flatMap(l=>l.steps||[]);nav.idx=0;drawRoute();showRouteSummary();}
catch(e){q('v21Next').textContent=e.message||'Routing error';}}
function drawRoute(){if(nav.route&&nav.map){if(nav.routeLayer)nav.map.removeLayer(nav.routeLayer);nav.routeLayer=L.geoJSON(nav.route.geometry,{style:{weight:7}}).addTo(nav.map);nav.map.fitBounds(nav.routeLayer.getBounds(),{padding:[20,20]})}}
function showRouteSummary(){let r=nav.route,mins=r.duration/60,miles=r.distance/1609.344;let now=new Date(),eta=new Date(now.getTime()+r.duration*1000);q('v21Miles').textContent=miles.toFixed(1)+' mi';q('v21Eta').textContent=fmt(eta);q('v21Arrival').textContent=fmt(eta);let hos=hosAvailable();let hEta=hos?new Date(now.getTime()+hosAwareSeconds(r.duration,hos)*1000):eta;q('v21HosEta').textContent=fmt(hEta);q('v21HOS').textContent=hos?`HOS ${Math.round(hos.drive*60)}m`:'HOS --';q('v21Next').textContent=nav.steps[0]?instruction(nav.steps[0]):'Continue on route';q('v21Road').textContent=nav.steps[0]?.name||'';routeAlerts();}
function fmt(d){return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function hosAvailable(){let st=load();let d=Number(st.driveRemaining??11),w=Number(st.shiftRemaining??14);if(!isFinite(d)||!isFinite(w))return null;return {drive:d,shift:w}}
function hosAwareSeconds(sec,h){let driveHours=sec/3600;let usable=Math.max(0,Math.min(h.drive,h.shift));if(driveHours<=usable)return sec;let breaks=Math.ceil((driveHours-usable)/usable);return sec+breaks*1800}
function instruction(x){let m=x.maneuver||{},t=m.type||'continue',mod=m.modifier||'';let map={turn:'Turn',merge:'Merge',fork:'Keep',roundabout:'Roundabout',depart:'Depart',arrive:'Arrive',newName:'Continue',continue:'Continue'};return `${map[t]||'Continue'}${mod?' '+mod:''}${x.name?' onto '+x.name:''}`}
function updateNav(){if(!nav.route||!nav.last)return;let best=Infinity,bi=nav.idx;for(let i=Math.max(0,nav.idx-1);i<Math.min(nav.steps.length,nav.idx+8);i++){let g=nav.steps[i].geometry?.coordinates||[];for(let p of g){let d=dist(nav.last.lat,nav.last.lon,p[1],p[0]);if(d<best){best=d;bi=i}}}if(best>0.35){routeRerouteNotice();return}if(bi!==nav.idx){nav.idx=bi;let x=nav.steps[bi];q('v21Next').textContent=instruction(x);q('v21Road').textContent=x.name||'Road';}}
let rerouteAt=0;function routeRerouteNotice(){if(Date.now()-rerouteAt<60000)return;rerouteAt=Date.now();let a=q('v21Alerts');if(a)a.innerHTML='<div class="v21warn">⚠️ Off route — checking for a new route.</div>';go()}
async function routeAlerts(){let r=nav.route;if(!r)return;let box=q('v21Alerts');box.innerHTML='<div class="v21ok">🧭 Route loaded. Checking public road/weather intelligence…</div>';try{let lat=nav.dest.lat,lon=nav.dest.lon;let w=await fetch(`https://api.weather.gov/points/${lat},${lon}`).then(x=>x.json());let f=await fetch(w.properties.forecast).then(x=>x.json());let p=f.properties.periods[0];box.innerHTML+=`<div class="v21item">🌦️ Destination weather: ${esc(p.name)} — ${esc(p.temperature)}°${esc(p.temperatureUnit)}, ${esc(p.shortForecast)}. ${esc(p.windSpeed)} ${esc(p.windDirection)}.</div>`}catch{}box.innerHTML+=`<div class="v21item">🚛 Truck restrictions: public OSRM route is ordinary vehicle routing. Height/weight/axle restrictions must be verified before departure.</div>`}
async function findPOI(type){let center=nav.last;if(!center)return alert('GPS is needed for nearby stops.');let tag=type==='fuel'?'amenity=fuel':type==='parking'?'amenity=parking':type==='rest'?'highway=rest_area':type==='repair'?'shop=car_repair':'amenity=parking';let query=`[out:json][timeout:12];(node[${tag}](around:20000,${center.lat},${center.lon});way[${tag}](around:20000,${center.lat},${center.lon}););out center tags;`;try{let d=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:query}).then(r=>r.json());let arr=(d.elements||[]).slice(0,12);let box=q('v21Alerts');box.innerHTML='<div class="card"><h3>Nearby '+esc(type)+'</h3><div class="v21list">'+arr.map(x=>{let lat=x.lat??x.center?.lat,lon=x.lon??x.center?.lon,n=x.tags?.name||type.replace('_',' ');return `<div class="v21item"><b>${esc(n)}</b><div class="v21small">${dist(center.lat,center.lon,lat,lon).toFixed(1)} km away</div><button onclick="window.open('https://www.google.com/maps/search/?api=1&query=${lat},${lon}','_blank')">NAVIGATE</button></div>`}).join('')+'</div></div>'}catch(e){q('v21Alerts').innerHTML='<div class="v21warn">Stop search unavailable right now.</div>'}}
function truckSheet(){let st=load();let m=document.createElement('div');m.className='v21modal';m.innerHTML=`<div class="v21sheet"><h2>🚛 Truck Profile</h2><p class="v21small">These values are planning inputs only. The public route engine does not enforce them.</p><div class="v21grid"><label>Height<input id="tH" value="${esc(st.height||'')}"></label><label>Width<input id="tW" value="${esc(st.width||'')}"></label><label>Length<input id="tL" value="${esc(st.length||'')}"></label><label>Gross weight<input id="tGW" value="${esc(st.weight||'')}"></label><label>Axles<input id="tA" value="${esc(st.axles||'')}"></label><label>Trailer<input id="tT" value="${esc(st.trailer||'')}"></label><label>Hazmat<select id="tHM"><option value="no">No</option><option value="yes">Yes</option></select></label></div><button id="tSave">SAVE PROFILE</button> <button id="tClose">CLOSE</button></div>`;document.body.appendChild(m);q('tHM').value=st.hazmat?'yes':'no';q('tSave').onclick=()=>{s=load();Object.assign(s,{height:q('tH').value,width:q('tW').value,length:q('tL').value,weight:q('tGW').value,axles:q('tA').value,trailer:q('tT').value,hazmat:q('tHM').value==='yes'});save(s);m.remove()};q('tClose').onclick=()=>m.remove()}
function intelSheet(){let m=document.createElement('div');m.className='v21modal';m.innerHTML=`<div class="v21sheet"><h2>⚠️ Route Intelligence</h2><div class="v21list"><div class="v21item">🚧 Construction / closures — connect a state 511 or WZDx feed for live event data.</div><div class="v21item">🌉 Bridge clearance — verify every posted clearance against your truck height.</div><div class="v21item">⚖️ Weight / axle restrictions — verify posted limits and permit requirements.</div><div class="v21item">🌨️ Weather — NWS destination forecast is checked when available.</div><div class="v21item">⛽ Fuel — combine tank/MPG/fuel percentage in Settings for planning.</div><div class="v21item">🅿️ Parking — nearby public OSM parking can be searched; availability is not guaranteed.</div><div class="v21item">📡 Live traffic — requires a live traffic provider/API; this prototype does not fabricate traffic data.</div></div><button id="iClose">CLOSE</button></div>`;document.body.appendChild(m);q('iClose').onclick=()=>m.remove()}
window.HOS150DriverOS={go,findPOI};setTimeout(install,1200);
})();
