/* HOS 150 Driver Companion V31.4 — stable PWA shell */
(()=>{'use strict';
const APP='HOS 150 Driver Companion V31.4';
function brand(){document.title=APP;const d=document.querySelector('meta[name="description"]');if(d)d.content='HOS, truck navigation, GPS, trip planning, weather, driver tools, customer address book and 150-air-mile companion for professional drivers.';document.querySelectorAll('meta[name="app-version"],meta[name="build-id"]').forEach(x=>x.setAttribute('content',x.name==='app-version'?'31.4':'2026-09-10-v31.4'));let m=document.querySelector('link[rel="manifest"]');if(m)m.href='manifest.webmanifest?v=31.4';if(!document.querySelector('meta[name="apple-mobile-web-app-capable"]')){let a=document.createElement('meta');a.name='apple-mobile-web-app-capable';a.content='yes';document.head.appendChild(a)}if(!document.querySelector('meta[name="apple-mobile-web-app-status-bar-style"]')){let a=document.createElement('meta');a.name='apple-mobile-web-app-status-bar-style';a.content='black-translucent';document.head.appendChild(a)}if(!document.querySelector('meta[name="apple-mobile-web-app-title"]')){let a=document.createElement('meta');a.name='apple-mobile-web-app-title';a.content=APP;document.head.appendChild(a)}}
function visual(){if(document.getElementById('v31navvisual'))return;const s=document.createElement('style');s.id='v31navvisual';s.textContent=`.n28actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px!important;margin-top:10px!important}.n28actions .n28btn{min-height:48px!important;border:2px solid #cbd5e1!important;background:#fff!important;color:#0f172a!important;box-shadow:0 4px 12px #0f172a22!important;font-size:14px!important;font-weight:900!important;text-shadow:none!important}.n28actions .n28btn:active{transform:scale(.98);background:#e0f2fe!important}.n28actions #n28voice{border-color:#93c5fd!important}.n28actions #n28report{border-color:#fbbf24!important}.n28actions #n28truck{border-color:#94a3b8!important}.n28actions #n28recenter{border-color:#60a5fa!important}`;document.head.appendChild(s)}
function loadRouting(){if(document.querySelector('script[data-customer-routing-v31]'))return;const s=document.createElement('script');s.src='customer-routing-v31.js?v=31.4';s.dataset.customerRoutingV31='1';document.body.appendChild(s)}
function installButton(){if(window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone)return;if(document.getElementById('pwaInstall'))return;const b=document.createElement('button');b.id='pwaInstall';b.textContent='📲 INSTALL APP';b.className='secondary';b.style.cssText='position:fixed;right:10px;top:10px;z-index:99999;font-weight:800;box-shadow:0 3px 12px rgba(0,0,0,.25)';let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});b.onclick=async()=>{if(deferred){deferred.prompt();try{await deferred.userChoice}catch{}deferred=null;return}alert('On iPhone: tap the Share button in Safari, then choose “Add to Home Screen”. On Android: use the browser menu and choose “Install app” or “Add to home screen”.')};document.body.appendChild(b)}
function sw(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=31.5').catch(()=>{})}
function boot(){brand();visual();installButton();sw();loadRouting()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
