(()=>{'use strict';
const q=id=>document.getElementById(id),K='hos150v13';
let map=null,route=null,routeLayer=null,routeCoords=[],steps=[],gps=null,gpsMarker=null,gpsAccuracy=null,watch=null,following=true,lastPan=0,lastGpsAt=0,destination=null,voiceOn=true,rerouteBusy=false;
const S=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function style(){if(q('n27css'))return;let s=document.createElement('style');s.id='n27css';s.textContent=`#route.n27{margin:0;padding:0;background:#f6f7f9;color:#111827;min-height:calc(100vh - 100px);overflow:hidden}.n27bar{position:relative;z-index:1000;padding:10px;background:rgba(255,255,255,.96);backdrop-filter:blur(18px);border-bottom:1px solid #e5e7eb}.n27search{display:flex;gap:7px}.n27search input{flex:1;height:48px;border:1px solid #d1d5db;border-radius:14px;padding:0 14px;font-size:17px;outline:none;box-shadow:0 1px 3px #0001}.n27btn{border:0;border-radius:13px;min-height:44px;padding:0 14px;font-weight:800;background:#fff;box-shadow:0 2px 8px #0002}.n27go{background:#111827;color:#fff}.n27chips{display:flex;gap:6px;overflow:auto;margin-top:8px}.n27chip{white-space:nowrap;border-radius:18px;padding:6px 10px;background:#eef2f7;font-size:12px;font-weight:800}.n27map{height:calc(100vh - 325px);min-height:390px;position:relative}.n27map .leaflet-control-attribution{font-size:9px}.n27loc{position:absolute;right:14px;top:132px;z-index:900;width:48px;height:48px;border:0;border-radius:50%;background:#fff;box-shadow:0 3px 14px #0003;font-size:23px}.n27sheet{position:relative;z-index:950;margin-top:-1px;background:#fff;border-radius:24px 24px 0 0;box-shadow:0 -5px 25px #0002;padding:12px 14px calc(12px + env(safe-area-inset-bottom));max-height:255px}.n27handle{width:38px;height:4px;border-radius:4px;background:#d1d5db;margin:0 auto 10px}.n27turn{display:flex;align-items:center;gap:11px}.n27turnicon{width:52px;height:52px;border-radius:15px;background:#111827;color:#fff;display:grid;place-items:center;font-size:31px}.n27turntext{min-width:0;flex:1}.n27turntext b{display:block;font-size:17px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.n27turntext small{color:#6b7280}.n27stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:10px 0}.n27stat{background:#f1f3f6;border-radius:12px;padding:7px;text-align:center}.n27stat small{display:block;color:#6b7280;font-size:9px;font-weight:800}.n27stat strong{font-size:17px}.n27actions{display:flex;gap:7px;overflow:auto}.n27actions .n27btn{white-space:nowrap;min-height:40px}.n27routeinfo{font-size:11px;color:#6b7280;margin-top:7px}.n27status{position:absolute;left:12px;top:12px;z-index:900;background:rgba(17,24,39,.9);color:#fff;border-radius:16px;padding:8px 11px;font-size:12px;font-weight:800;box-shadow:0 3px 12px #0003}.n27dot{width:22px;height:22px;border-radius:50%;background:#1683ff;border:4px solid #fff;box-shadow:0 2px 8px #0005}.n27pulse{width:44px;height:44px;border-radius:50%;background:#1683ff22;border:1px solid #1683ff55;transform:translate(-50%,-50%)}@media(max-width:650px){.n27map{height:calc(100vh - 340px)}.n27sheet{max-height:270px}}`;document.head.appendChild(s)}
function render(){let r=q('route');if(!r)return;r.className='screen n27';r.innerHTML=`<div class="n27bar"><div class="n27search"><input id="n27dest" placeholder="Where to?"><button id="n27go" class="n27btn n27go">GO</button><button id="n27menu" class="n27btn">☰</button></div><div class="n27chips"><span id="n27gps" class="n27chip">● GPS</span><span id="n27speed" class="n27chip">0 MPH</span><span id="n27hos" class="n27chip">HOS --</span><span id="n27air" class="n27chip">150 AIR --</span></div></div><div id="n27map" class="n27map"><div id="n27status" class="n27status">Waiting for GPS…</div></div><button id="n27loc" class="n27loc">◎</button><div class="n27sheet"><div class="n27handle"></div><div class="n27turn"><div id="n27turnIcon" class="n27turnicon">↑</div><div class="n27turntext"><b id="n27next">Ready to navigate</b><small id="n27dist">Enter a destination</small></div></div><div class="n27stats"><div class="n27stat"><small>ARRIVAL</small><strong id="n27eta">--</strong></div><div class="n27stat"><small>REMAINING</small><strong id="n27miles">--</strong></div><div class="n27stat"><small>HOS ARRIVAL</small><strong id="n27hoseta">--</strong></div></div><div class="n27actions"><button id="n27recenter" class="n27btn">◎ Recenter</button><button id="n27voice" class="n27btn">🔊 Voice</button><button id="n27report" class="n27btn">⚠️ Report</button><button id="n27truck" class="n27btn">🚛 Truck</button></div><div id="n27routeinfo" class="n27routeinfo">Live GPS • smooth tracking • automatic rerouting</div></div>`;init()}
function init(){if(!window.L)return;map=L.map('n27map',{zoomControl:false,zoomAnimation:true,fadeAnimation:true,markerZoomAnimation:true,preferCanvas:true,inertia:true,inertiaDeceleration:2800,inertiaMaxSpeed:1500,zoomSnap:.25,zoomDelta:.5}).setView([39.5,-98.35],4);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,updateWhenZooming:false,updateWhenIdle:true,keepBuffer:4,attribution:'© OpenStreetMap'}).addTo(map);map.on('dragstart',()=>{following=false;status('Manual map mode')});map.on('zoomstart',()=>{});q('n27go').onclick=go;q('n27dest').onkeydown=e=>{if(e.key==='Enter')go()};q('n27loc').onclick=recenter;q('n27recenter').onclick=recenter;q('n27voice').onclick=()=>{voiceOn=!voiceOn;q('n27voice').textContent=voiceOn?'🔊 Voice':'🔇 Voice'};q('n27report').onclick=()=>alert('Driver reports are being connected to the live road intelligence engine.');q('n27truck').onclick=()=>alert('Truck profile controls will be connected here.');startGPS();setTimeout(()=>map.invalidateSize(),250)}
function startGPS(){if(!navigator.geolocation){status('GPS unavailable');return}watch=navigator.geolocation.watchPosition(onGPS,()=>{q('n27gps').textContent='● GPS unavailable';status('Location permission required')},{enableHighAccuracy:true,maximumAge:500,timeout:10000})}
function onGPS(p){let c=p.coords;let next={lat:c.latitude,lon:c.longitude,speed:Math.max(0,(c.speed||0)*2.236936),accuracy:c.accuracy||99,heading:Number.isFinite(c.heading)?c.heading:null,time:performance.now()};if(!gps){gps=next;createMarker();}else{gps=next;moveMarker();}q('n27gps').textContent='● GPS ±'+Math.round(gps.accuracy)+'m';q('n27speed').textContent=Math.round(gps.speed)+' MPH';lastGpsAt=performance.now();air();hosChip();if(following)follow();if(route){updateNavigation();if(isOffRoute()&&!rerouteBusy)reroute()}}
function createMarker(){let icon=L.divIcon({className:'',html:'<div class="n27pulse"></div><div class="n27dot"></div>',iconSize:[1,1],iconAnchor:[0,0]});gpsMarker=L.marker([gps.lat,gps.lon],{icon,zIndexOffset:1000,interactive:false}).addTo(map);gpsAccuracy=L.circle([gps.lat,gps.lon],{radius:Math.min(gps.accuracy,80),color:'#1683ff',weight:1,fillOpacity:.06,interactive:false}).addTo(map)}
function moveMarker(){if(!gpsMarker)return;let old=gpsMarker.getLatLng();let target=L.latLng(gps.lat,gps.lon),start=performance.now(),dur=450;function f(t){let k=Math.min(1,(t-start)/dur),e=k*(2-k);let lat=old.lat+(target.lat-old.lat)*e,lon=old.lng+(target.lng-old.lng)*e;gpsMarker.setLatLng([lat,lon]);gpsAccuracy?.setLatLng([lat,lon]).setRadius(Math.min(gps.accuracy,80));if(k<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
function follow(){if(!map||!gps)return;if(performance.now()-lastPan<650)return;lastPan=performance.now();let z=map.getZoom();if(z<14)z=15.5;map.panTo([gps.lat,gps.lon],{animate:true,duration:.45,noMoveStart:true});if(map.getZoom()!==z&&map.getZoom()<14)map.setZoom(z,{animate:true,duration:.35})}
function recenter(){if(!gps)return;following=true;map.flyTo([gps.lat,gps.lon],Math.max(15.5,map.getZoom()),{animate:true,duration:.7,easeLinearity:.25});status('Following your truck')}
async function geo(t){let r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q='+encodeURIComponent(t),{headers:{Accept:'application/json'}}),a=await r.json();if(!a[0])throw Error('Destination not found');return{lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name}}
async function go(){let t=q('n27dest').value.trim();if(!t)return;if(!gps){status('Waiting for GPS…');return}q('n27next').textContent='Finding the best route…';try{destination=await geo(t);await buildRoute();}catch(e){q('n27next').textContent=e.message||'Routing failed';status('Route unavailable')}}
async function buildRoute(){let u=`https://router.project-osrm.org/route/v1/driving/${gps.lon},${gps.lat};${destination.lon},${destination.lat}?overview=full&geometries=geojson&steps=true&annotations=true`;let j=await fetch(u).then(x=>x.json());if(j.code!=='Ok')throw Error('No route found');route=j.routes[0];routeCoords=route.geometry.coordinates;steps=(route.legs||[]).flatMap(l=>l.steps||[]);if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(route.geometry,{style:{weight:12,opacity:.18,lineCap:'round',lineJoin:'round'}}).addTo(map);L.geoJSON(route.geometry,{style:{weight:6,opacity:.95,lineCap:'round',lineJoin:'round'}}).addTo(routeLayer);map.fitBounds(routeLayer.getBounds(),{padding:[20,150],animate:true,duration:.8});updateStats();updateNavigation();status('Route ready');speak('Route ready. '+Math.round(route.distance/1609.344)+' miles.')} 
function updateStats(){if(!route)return;let miles=route.distance/1609.344,eta=new Date(Date.now()+route.duration*1000);q('n27miles').textContent=miles.toFixed(1)+' mi';q('n27eta').textContent=clock(eta);q('n27hoseta').textContent=clock(hosETA(route.duration));q('n27routeinfo').textContent=`${Math.round(route.duration/60)} min • ${miles.toFixed(1)} mi • live rerouting enabled`}
function updateNavigation(){if(!route||!gps)return;let idx=nearestIndex(),remaining=route.distance;let frac=Math.max(0,idx/Math.max(1,routeCoords.length-1));remaining=route.distance*(1-frac);q('n27miles').textContent=(remaining/1609.344).toFixed(1)+' mi';let si=nearestStep();if(si>=0){let st=steps[si],name=st.name||'the road ahead',distM=st.maneuver?.location?distToStep(st):0;q('n27next').textContent=instruction(st);q('n27dist').textContent=distM>0?Math.round(distM*3.28084)+' ft • '+name:name;q('n27turnIcon').textContent=arrowFor(st.maneuver?.type,st.maneuver?.modifier)} }
function nearestIndex(){let best=0,bd=1e9;for(let i=0;i<routeCoords.length;i++){let p=routeCoords[i],d=dist(gps.lat,gps.lon,p[1],p[0]);if(d<bd){bd=d;best=i}}return best}
function nearestStep(){if(!steps.length)return -1;let best=0,bd=1e9;for(let i=0;i<steps.length;i++){let l=steps[i].maneuver?.location;if(!l)continue;let d=dist(gps.lat,gps.lon,l[1],l[0]);if(d<bd){bd=d;best=i}}return best}
function distToStep(st){let l=st.maneuver.location;return dist(gps.lat,gps.lon,l[1],l[0])*1000}
function instruction(st){let m=st.maneuver||{},mod=m.modifier||'';if(m.type==='arrive')return'Arrive at destination';if(m.type==='depart')return'Head toward your destination';if(m.type==='roundabout'||m.type==='rotary')return`Enter roundabout${m.exit?`, take exit ${m.exit}`:''}`;let x=mod.replace('uturn','U-turn').replace('sharp left','sharp left').replace('sharp right','sharp right');return x?`Turn ${x}`:'Continue straight'}
function arrowFor(t,m){if(t==='arrive')return'✓';if(t==='roundabout'||t==='rotary')return'↻';if(m?.includes('left'))return'↰';if(m?.includes('right'))return'↱';if(m==='uturn')return'↶';return'↑'}
function isOffRoute(){let i=nearestIndex();return dist(gps.lat,gps.lon,routeCoords[i][1],routeCoords[i][0])>0.8}
async function reroute(){rerouteBusy=true;status('Recalculating route…');try{await buildRoute();speak('Route updated')}catch{}finally{rerouteBusy=false}}
function hosChip(){let s=S(),h=Number(s.cycleStart);q('n27hos').textContent='HOS '+(Number.isFinite(h)?h.toFixed(1)+'h':'--')}
function hosETA(seconds){let s=S(),dr=Number(s.driveLeftHours||11);if(!Number.isFinite(dr)||dr<=0)return new Date(Date.now()+seconds*1000);let driving=Math.min(seconds/3600,dr),extra=seconds/3600>dr?1800:0;return new Date(Date.now()+(seconds+extra)*1000)}
function air(){let b=S().baseCoords;if(!gps||!b){q('n27air').textContent='150 AIR --';return}let d=dist(gps.lat,gps.lon,b.lat,b.lon)*.621371;q('n27air').textContent='150 AIR '+(d<=172.6?'IN ':'OUT ')+d.toFixed(1)+'mi'}
function dist(a,b,c,d){let R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function clock(d){return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function status(t){let x=q('n27status');if(!x)return;x.textContent=t;x.style.opacity='1';clearTimeout(status.t);status.t=setTimeout(()=>x.style.opacity='.0',2600)}
function speak(t){if(!voiceOn||!window.speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.95;u.pitch=1;speechSynthesis.speak(u)}
function install(){style();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
