/* TRUCKWAZE V25 — Waze-style truck navigation cockpit. Prototype only. */
(()=>{'use strict';
const K='hos150v13',q=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}},put=s=>localStorage.setItem(K,JSON.stringify(s));
let n={map:null,pos:null,marker:null,route:null,alt:null,layer:null,altLayer:null,steps:[],i:0,dest:null,watch:null,voice:true,follow:true,lastSay:0,lastReroute:0,reports:[],weather:null};
const types={accident:['💥','Accident'],construction:['🚧','Construction'],closure:['⛔','Road closed'],pothole:['🕳️','Pothole'],police:['👮','Police'],traffic:['🚦','Heavy traffic'],truck:['🚛','Truck hazard'],clearance:['↕️','Low clearance'],weight:['⚖️','Weight restriction'],parking:['🅿️','Parking issue'],weather:['🌨️','Dangerous weather'],debris:['🪨','Debris / road hazard']};
function css(){if(q('tw25css'))return;let s=document.createElement('style');s.id='tw25css';s.textContent=`#route.tw25{padding:0;margin:-8px;background:#07111f;min-height:calc(100vh - 150px)}.tw25top{position:sticky;top:0;z-index:800;background:#0b1322;color:#fff;padding:10px;border-bottom:1px solid #334155}.tw25search{display:flex;gap:7px}.tw25search input{flex:1;min-width:0;padding:13px;border:0;border-radius:13px;font-size:16px}.tw25b{padding:10px 12px;border:0;border-radius:12px;font-weight:900;background:#e2e8f0;color:#0f172a}.tw25go{background:#22c55e;color:#052e16}.tw25status{display:flex;gap:5px;overflow:auto;padding-top:8px}.tw25pill{white-space:nowrap;background:#1e293b;border-radius:999px;padding:5px 8px;font-size:11px;font-weight:800}.tw25map{height:48vh;min-height:390px}.tw25panel{background:#fff;border-radius:20px 20px 0 0;margin-top:-16px;position:relative;z-index:10;padding:12px}.tw25turn{display:flex;gap:10px;align-items:center;background:#0b1322;color:#fff;border-radius:15px;padding:10px}.tw25arrow{font-size:38px;min-width:48px;text-align:center}.tw25stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:8px 0}.tw25stat{background:#172033;color:#fff;border-radius:11px;padding:8px;text-align:center}.tw25stat small{font-size:10px;opacity:.75}.tw25stat b{display:block;font-size:16px;margin-top:2px}.tw25chips{display:flex;gap:6px;overflow:auto;padding:6px 0}.tw25chips button{white-space:nowrap}.tw25grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.tw25card{background:#f8fafc;border:1px solid #dbe3ee;border-radius:12px;padding:9px}.tw25small{font-size:11px;color:#64748b}.tw25ok,.tw25warn,.tw25bad,.tw25info{padding:9px;border-radius:10px;margin:7px 0;font-weight:800}.tw25ok{background:#dcfce7;color:#166534}.tw25warn{background:#fef3c7;color:#92400e}.tw25bad{background:#fee2e2;color:#991b1b}.tw25info{background:#e0f2fe;color:#075985}.tw25report{position:fixed;right:14px;bottom:92px;z-index:700;width:60px;height:60px;border:0;border-radius:50%;background:#f97316;color:#fff;font-size:25px;box-shadow:0 5px 18px #0008}.tw25modal{position:fixed;inset:0;background:#0009;z-index:9999;display:flex;align-items:flex-end}.tw25sheet{background:#fff;width:100%;max-height:90vh;overflow:auto;border-radius:20px 20px 0 0;padding:16px}.tw25list{display:grid;gap:7px}.tw25item{border:1px solid #dbe3ee;border-radius:11px;padding:9px}.tw25reportgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tw25reportgrid button{min-height:52px}.tw25mini{font-size:12px;color:#475569}.tw25routechoice{border:1px solid #cbd5e1;border-radius:12px;padding:9px;margin-top:7px}.tw25routechoice.active{border:2px solid #22c55e}.tw25danger{font-weight:900;color:#b91c1c}@media(max-width:650px){.tw25stats{grid-template-columns:repeat(2,1fr)}.tw25grid{grid-template-columns:1fr 1fr}.tw25map{height:47vh}}`;document.head.appendChild(s)}
function render(){let r=q('route');if(!r)return;r.className='screen tw25';r.innerHTML=`<div class="tw25top"><div class="tw25search"><input id="tw22dest" placeholder="Where to? address, city, ZIP"><button id="tw22go" class="tw25b tw25go">GO</button><button id="tw25menu" class="tw25b">☰</button></div><div class="tw25status"><span class="tw25pill" id="tw22speed">-- MPH</span><span class="tw25pill" id="tw22hos">HOS --</span><span class="tw25pill" id="tw22air">150 AIR --</span><span class="tw25pill" id="tw22gps">GPS --</span><span class="tw25pill" id="tw25routeState">READY</span></div></div><div id="tw22map" class="tw25map"></div><div class="tw25panel"><div class="tw25turn"><div id="tw22arrow" class="tw25arrow">⬆️</div><div><b id="tw22next">Enter a destination</b><div id="tw22dist" class="tw25small">TruckWaze ready — GPS + route intelligence enabled</div></div></div><div class="tw25stats"><div class="tw25stat"><small>ETA</small><b id="tw22eta">--</b></div><div class="tw25stat"><small>ROAD MILES</small><b id="tw22miles">--</b></div><div class="tw25stat"><small>HOS ETA</small><b id="tw22hoseta">--</b></div><div class="tw25stat"><small>ARRIVAL</small><b id="tw22arrival">--</b></div></div><div class="tw25chips"><button id="tw22voice" class="tw25b">🔊 Voice</button><button id="tw25intel" class="tw25b">🧠 Route Intel</button><button id="tw25traffic" class="tw25b">🚦 Live Intel</button><button id="tw25truck" class="tw25b">🚛 Truck</button><button id="tw25stops" class="tw25b">🛑 Stops</button></div><div id="tw22alerts"></div><div id="tw25routeChoices"></div><div class="tw25grid"><div class="tw25card"><b>🌦️ Weather</b><div id="tw25weather">Waiting for route</div></div><div class="tw25card"><b>🅿️ HOS Stop</b><div id="tw25hosstop">Calculating</div></div><div class="tw25card"><b>⛽ Fuel</b><div id="tw25fuel">Set fuel in Settings</div></div></div><div class="tw25chips"><button data-twstop="fuel" class="tw25b">⛽ Fuel</button><button data-twstop="parking" class="tw25b">🅿️ Parking</button><button data-twstop="rest" class="tw25b">🛏️ Rest</button><button data-twstop="repair" class="tw25b">🔧 Repair</button><button data-twstop="scale" class="tw25b">⚖️ Scale</button></div><div class="tw25small">TruckWaze V25 prototype • OSM/OSRM/Open-Meteo public services. Verify posted clearances, weights, hazmat restrictions, closures and local rules.</div></div><button id="tw22report" class="tw25report">⚠️</button>`;init()}
function init(){if(!window.L||n.map)return;n.map=L.map('tw22map',{zoomControl:false,attributionControl:true}).setView([39.5,-98.35],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(n.map);n.map.on('dragstart',()=>n.follow=false);bind();gps();loadReports()}
function bind(){q('tw22go').onclick=route;q('tw22dest').onkeydown=e=>{if(e.key==='Enter')route()};q('tw22voice').onclick=()=>{n.voice=!n.voice;q('tw22voice').textContent=n.voice?'🔊 Voice':'🔇 Muted';if(n.voice)say('Voice navigation on')};q('tw25intel').onclick=()=>intel();q('tw25traffic').onclick=()=>liveIntel();q('tw25truck').onclick=truck();q('tw25stops').onclick=()=>stops('parking');q('tw22report').onclick=report;q('tw25menu').onclick=menu;document.querySelectorAll('[data-twstop]').forEach(b=>b.onclick=()=>stops(b.dataset.twstop))}
function gps(){if(!navigator.geolocation){gpsFail();return}n.watch=navigator.geolocation.watchPosition(p=>{n.pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:Math.max(0,(p.coords.speed||0)*2.236936),heading:p.coords.heading,accuracy:p.coords.accuracy||0};let s=get();s.pos=n.pos;put(s);if(!n.marker)n.marker=L.circleMarker([n.pos.lat,n.pos.lon],{radius:8,weight:3}).addTo(n.map);else n.marker.setLatLng([n.pos.lat,n.pos.lon]);q('tw22speed').textContent=Math.round(n.pos.speed)+' MPH';q('tw22gps').textContent='GPS ±'+Math.round(n.pos.accuracy)+'m';radius();navUpdate();if(n.follow)n.map.setView([n.pos.lat,n.pos.lon],Math.max(14,n.map.getZoom()),{animate:true})},e=>gpsFail(),{enableHighAccuracy:true,maximumAge:1500,timeout:10000})}
function gpsFail(){if(q('tw22gps'))q('tw22gps').textContent='GPS unavailable';if(q('tw22alerts'))q('tw22alerts').innerHTML='<div class="tw25warn">📍 GPS unavailable. Enable iPhone Location for live position, motion, 150-air-mile and nearby stops.</div>'}
function km(a,b,c,d){let R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function radius(){let s=get(),b=s.baseCoords;if(!n.pos||!q('tw22air'))return;if(!b){q('tw22air').textContent='150 AIR SET BASE';return}let m=km(n.pos.lat,n.pos.lon,b.lat,b.lon)*.621371;q('tw22air').textContent='150 AIR '+(m<=172.6?'IN':'OUT')+' '+m.toFixed(1)+'mi'}
async function geocode(x){let r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q='+encodeURIComponent(x),{headers:{'Accept-Language':'en-US'}});if(!r.ok)throw Error('Address search unavailable');let a=await r.json();if(!a[0])throw Error('Destination not found');return{lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name}}
async function getRoutes(p,d){let u=`https://router.project-osrm.org/route/v1/driving/${p.lon},${p.lat};${d.lon},${d.lat}?overview=full&geometries=geojson&steps=true&alternatives=true&annotations=true`;let j=await fetch(u).then(r=>r.json());if(j.code!=='Ok')throw Error('Routing unavailable');return j.routes||[]}
async function route(){let text=q('tw22dest').value.trim(),p=n.pos||get().pos;if(!text){alert('Enter a destination.');return}if(!p){alert('Enable GPS or use the trip planner to set a starting point.');return}try{q('tw22next').textContent='Building truck route…';q('tw25routeState').textContent='ROUTING';let d=await geocode(text),rs=await getRoutes(p,d);if(!rs.length)throw Error('No route found');n.dest=d;n.route=rs[0];n.alt=rs[1]||null;selectRoute(0);let s=get();s.routeEnd=d.name;s.routeMiles=n.route.distance/1609.344;s.routeMinutes=n.route.duration/60;s.routeGeoJSON=n.route.geometry;s.routeSteps=n.steps;put(s);summary();await routeWeather();intel();say('Navigation started. '+next());q('tw25routeState').textContent='NAVIGATING'}catch(e){q('tw22next').textContent=e.message||'Route failed';q('tw25routeState').textContent='ERROR'}}
function selectRoute(which){let r=which===1?n.alt:n.route;if(!r)return;n.route=r;n.steps=r.legs.flatMap(x=>x.steps||[]).filter(x=>x.maneuver?.type!=='depart');n.i=0;if(n.layer)n.map.removeLayer(n.layer);if(n.altLayer)n.map.removeLayer(n.altLayer);if(n.alt&&which===0)n.altLayer=L.geoJSON(n.alt.geometry,{style:{weight:5,opacity:.45,dashArray:'8 8'}}).addTo(n.map);n.layer=L.geoJSON(r.geometry,{style:{weight:8,opacity:.95}}).addTo(n.map);n.map.fitBounds(n.layer.getBounds(),{padding:[20,140]});summary();renderChoices(which)}
function renderChoices(active=0){let b=q('tw25routeChoices');if(!b)return;let a=`<div class="tw25routechoice ${active===0?'active':''}"><b>🚛 Recommended route</b><div class="tw25mini">${(n.route.distance/1609.344).toFixed(1)} mi • ${Math.round(n.route.duration/60)} min • truck profile checks enabled</div></div>`;if(n.alt)a+=`<div class="tw25routechoice ${active===1?'active':''}"><b>↔️ Alternate route</b><div class="tw25mini">${(n.alt.distance/1609.344).toFixed(1)} mi • ${Math.round(n.alt.duration/60)} min</div><button id="tw25alt" class="tw25b">USE ALTERNATE</button></div>`;b.innerHTML=a;if(q('tw25alt'))q('tw25alt').onclick=()=>{n.route=n.alt;selectRoute(1)}}
function hos(){let s=get(),d=Number(s.driveRemaining),w=Number(s.shiftRemaining),c=Number(s.cycleRemaining);return{drive:isFinite(d)?Math.max(0,d):11,shift:isFinite(w)?Math.max(0,w):14,cycle:isFinite(c)?Math.max(0,c):70}}
function hosSec(sec){let h=hos(),left=sec/3600,total=0,dr=h.drive,sh=h.shift;while(left>0){let use=Math.min(left,dr,sh);if(use<=0){total+=1800;dr=11;sh=14;continue}total+=use*3600;left-=use;dr-=use;sh-=use;if(left>0){total+=1800;dr=11;sh=14}}return total}
function clock(d){return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function summary(){if(!n.route)return;let m=n.route.distance/1609.344,e=new Date(Date.now()+n.route.duration*1000),he=new Date(Date.now()+hosSec(n.route.duration)*1000);q('tw22miles').textContent=m.toFixed(1)+' mi';q('tw22eta').textContent=clock(e);q('tw22arrival').textContent=clock(e);q('tw22hoseta').textContent=clock(he);let h=hos();q('tw22hos').textContent='HOS '+Math.floor(h.drive)+':'+String(Math.round(h.drive%1*60)).padStart(2,'0');q('tw22next').textContent=next();q('tw22dist').textContent=stepDist();hosStop();fuelPlan()}
function next(){let x=n.steps[n.i];if(!x)return'Continue on route';let m=x.maneuver||{},t=m.type||'continue',mod=(m.modifier||'').replace('-',' '),v=t==='turn'?'Turn':t==='merge'?'Merge':t==='fork'?'Keep':t==='on ramp'?'Take ramp':t==='off ramp'?'Take exit':t==='roundabout'?`At roundabout, take ${m.exit||'the'} exit`:'Continue';return `${v}${mod?' '+mod:''}${x.name?' onto '+x.name:''}`}
function stepDist(){let x=n.steps[n.i],c=x?.maneuver?.location;if(!c||!n.pos)return'';let m=km(n.pos.lat,n.pos.lon,c[1],c[0])*.621371;return m<1?Math.round(m*5280)+' ft':m.toFixed(1)+' mi'}
function navUpdate(){if(!n.route||!n.pos)return;let x=n.steps[n.i],c=x?.maneuver?.location,d=c?km(n.pos.lat,n.pos.lon,c[1],c[0])*.621371:99;if(d<.03&&n.i<n.steps.length-1){n.i++;n.lastSay=0}q('tw22next').textContent=next();q('tw22dist').textContent=stepDist();q('tw22arrow').textContent=({'left':'↰','right':'↱','slight left':'↖️','slight right':'↗️','sharp left':'⬅️','sharp right':'➡️','straight':'⬆️'}[x?.maneuver?.modifier]||'⬆️');if(d<.15&&Date.now()-n.lastSay>12000){say(next()+' in '+stepDist());n.lastSay=Date.now()}if(offset()>0.15&&Date.now()-n.lastReroute>45000){n.lastReroute=Date.now();say('Off route. Recalculating.');route()}}
function offset(){if(!n.route||!n.pos)return 0;let a=n.route.geometry.coordinates,b=Infinity,step=Math.max(1,Math.floor(a.length/400));for(let i=0;i<a.length;i+=step)b=Math.min(b,km(n.pos.lat,n.pos.lon,a[i][1],a[i][0])*.621371);return b}
function say(t){if(!n.voice||!window.speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.98;u.volume=1;speechSynthesis.speak(u)}
function truck(){let s=get();sheet('🚛 Truck profile',`<div class="tw25info">Truck-aware prototype routing uses your profile for warnings and planning. The public OSRM route itself is not a certified truck-routing engine.</div><div class="tw25list"><div class="tw25item"><b>Height</b><br>${esc(s.height||'Not set')}</div><div class="tw25item"><b>Gross weight</b><br>${esc(s.weight||'Not set')}</div><div class="tw25item"><b>Axles</b><br>${esc(s.axles||'Not set')}</div><div class="tw25item"><b>Trailer</b><br>${esc(s.trailer||'Not set')}</div></div><button class="tw25b" onclick="document.querySelector('[data-tab=\"settings\"]').click()">EDIT TRUCK PROFILE</button>`)}
async function routeWeather(){if(!n.route)return;let pts=n.route.geometry.coordinates,idx=[0,.25,.5,.75,1].map(v=>pts[Math.min(pts.length-1,Math.floor((pts.length-1)*v))]);q('tw25weather').textContent='Checking route weather…';try{let vals=await Promise.all(idx.map(async p=>{let u=`https://api.open-meteo.com/v1/forecast?latitude=${p[1]}&longitude=${p[0]}&current=temperature_2m,precipitation,wind_speed_10m,weather_code&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`;let j=await fetch(u).then(r=>r.json());return j.current}));let maxWind=Math.max(...vals.map(x=>x.wind_speed_10m||0)),precip=Math.max(...vals.map(x=>x.precipitation||0)),temp=vals[Math.floor(vals.length/2)]?.temperature_2m;q('tw25weather').innerHTML=`${Math.round(temp??0)}°F • wind ${Math.round(maxWind)} mph${precip>0?' • precipitation on route':''}`+(maxWind>=35?'<div class="tw25warn">⚠️ High wind risk — verify conditions.</div>':'');}catch{q('tw25weather').textContent='Weather service unavailable'}}
function hosStop(){let h=hos(),m=n.route?n.route.distance/1609.344:0,usable=Math.min(h.drive,h.shift),time=m/55;if(time<=usable){q('tw25hosstop').innerHTML='<span class="tw25ok">No HOS stop required by prototype estimate.</span>';return}let miles=Math.max(0,usable*55);q('tw25hosstop').innerHTML=`<span class="tw25warn">Plan a break/rest stop in about ${miles.toFixed(0)} route miles.</span>`}
function fuelPlan(){let s=get(),tank=Number(s.tanks),mpg=Number(s.mpg),pct=Number(s.fuelPct);if(!tank||!mpg||!isFinite(pct)){q('tw25fuel').textContent='Set tank gallons, MPG and fuel % in Settings';return}let range=tank*mpg*pct/100;q('tw25fuel').textContent=`Approx. ${Math.round(range)} miles remaining at ${mpg} MPG`}
async function stops(type){if(!n.pos){alert('GPS needed for nearby stops.');return}let tag=type==='fuel'?'amenity=fuel':type==='parking'?'amenity=parking':type==='rest'?'highway=rest_area':type==='repair'?'shop=car_repair':'amenity=parking';let qs=`[out:json][timeout:15];(node[${tag}](around:30000,${n.pos.lat},${n.pos.lon});way[${tag}](around:30000,${n.pos.lat},${n.pos.lon}););out center tags;`;try{let j=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:qs}).then(r=>r.json()),a=(j.elements||[]).map(e=>{let lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;return{lat,lon,name:e.tags?.name||type,d:km(n.pos.lat,n.pos.lon,lat,lon)}}).filter(x=>x.lat).sort((a,b)=>a.d-b.d).slice(0,15);sheet('🛑 '+type,a.map(x=>`<div class="tw25item"><b>${esc(x.name)}</b><div class="tw25small">${(x.d*.621371).toFixed(1)} mi away</div><button class="tw25b" onclick="window.open('https://www.google.com/maps/search/?api=1&query=${x.lat},${x.lon}','_blank')">NAVIGATE</button></div>`).join('')||'No nearby results.')}catch{sheet('Stops','<div class="tw25bad">Nearby stop service unavailable.</div>')}}
function liveIntel(){let r=n.reports.filter(x=>!n.pos||km(n.pos.lat,n.pos.lon,x.lat,x.lon)*.621371<50).sort((a,b)=>b.t-a.t);sheet('🚦 Live Driver Intel',`<div class="tw25info">This prototype shows reports stored on this phone. A shared Waze-style network needs a server/database; the report format is ready for that next step.</div>${r.length?r.map(x=>{let z=types[x.type]||['⚠️',x.type];return `<div class="tw25item"><b>${z[0]} ${z[1]}</b><div>${esc(x.note||'Driver report')}</div><div class="tw25small">${n.pos?((km(n.pos.lat,n.pos.lon,x.lat,x.lon)*.621371).toFixed(1)+' mi away • '):''}${new Date(x.t).toLocaleTimeString()}</div></div>`}).join(''):'<div class="tw25small">No local reports yet.'}`)}
function intel(){let alerts=[];if(n.route){let h=hos();if(Math.min(h.drive,h.shift)<2)alerts.push('<div class="tw25warn">⏱️ Less than 2 hours of usable HOS — plan a safe stop.</div>');if(n.alt&&n.alt.duration<n.route.duration)alerts.push('<div class="tw25info">↔️ An alternate route is available.</div>')}let near=n.reports.filter(x=>n.pos&&km(n.pos.lat,n.pos.lon,x.lat,x.lon)*.621371<25);if(near.length)alerts.push(`<div class="tw25warn">⚠️ ${near.length} driver report${near.length>1?'s':''} within 25 miles.</div>`);q('tw22alerts').innerHTML=alerts.join('')||'<div class="tw25ok">🧠 Route Intel: no prototype alerts right now.</div>'}
function report(){if(!n.pos){alert('GPS is needed to place a report.');return}sheet('⚠️ Report for other truckers',`<p class="tw25mini">Your report is saved with your GPS position and time.</p><div class="tw25reportgrid">${Object.entries(types).map(([k,v])=>`<button class="tw25b" data-report="${k}">${v[0]} ${v[1]}</button>`).join('')}</div><textarea id="tw25note" rows="3" placeholder="Optional details"></textarea>`);document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>saveReport(b.dataset.report))}
function saveReport(type){let a=get();a.driverReports=Array.isArray(a.driverReports)?a.driverReports:[];let x={type,lat:n.pos.lat,lon:n.pos.lon,t:Date.now(),note:q('tw25note')?.value.trim()||''};a.driverReports.unshift(x);a.driverReports=a.driverReports.slice(0,200);put(a);n.reports=a.driverReports;closeSheet();addReportMarker(x);intel();say('Driver report saved')}
function loadReports(){let s=get();n.reports=Array.isArray(s.driverReports)?s.driverReports:[];n.reports.forEach(addReportMarker)}
function addReportMarker(x){if(!n.map)return;let z=types[x.type]||['⚠️','Report'];L.marker([x.lat,x.lon]).addTo(n.map).bindPopup(`<b>${z[0]} ${z[1]}</b><br>${esc(x.note||'Driver report')}<br><small>${new Date(x.t).toLocaleString()}</small>`)}
function menu(){sheet('☰ TruckWaze',`<div class="tw25list"><button class="tw25b" onclick="window.TW25?.liveIntel()">🚦 Driver reports</button><button class="tw25b" onclick="window.TW25?.truck()">🚛 Truck profile</button><button class="tw25b" onclick="window.TW25?.stops('parking')">🅿️ Find parking</button><button class="tw25b" onclick="window.TW25?.stops('fuel')">⛽ Find fuel</button><button class="tw25b" onclick="document.querySelector('[data-tab=\"settings\"]').click();window.TW25?.closeSheet()">⚙️ Settings</button></div>`)}
function sheet(title,body){closeSheet();let d=document.createElement('div');d.id='tw25modal';d.className='tw25modal';d.innerHTML=`<div class="tw25sheet"><div style="display:flex;justify-content:space-between;align-items:center"><h2>${title}</h2><button id="tw25close" class="tw25b">✕</button></div><div class="tw25list">${body}</div></div>`;document.body.appendChild(d);q('tw25close').onclick=closeSheet;d.onclick=e=>{if(e.target===d)closeSheet()}}
function closeSheet(){q('tw25modal')?.remove()}
window.TW25={route,truck,stops,liveIntel,intel,report,closeSheet};
function install(){css();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,350));else setTimeout(install,350);
})();