/* TRUCKWAZE V22 — Waze-style truck navigation companion. Prototype only. */
(()=>{'use strict';
const K='hos150v13',Q=id=>document.getElementById(id),get=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}},put=s=>localStorage.setItem(K,JSON.stringify(s));
let n={map:null,pos:null,marker:null,route:null,layer:null,steps:[],i:0,dest:null,watch:null,voice:true,follow:true,lastSay:0,lastReroute:0};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function style(){if(Q('tw22css'))return;let s=document.createElement('style');s.id='tw22css';s.textContent=`#route.tw22{padding:0;margin:-8px;background:#0b1220;min-height:calc(100vh - 150px)}.tw22top{position:sticky;top:0;z-index:800;background:#111827;color:white;padding:9px}.tw22search{display:flex;gap:6px}.tw22search input{flex:1;min-width:0;padding:12px;border:0;border-radius:12px;font-size:16px}.tw22b{padding:10px 12px;border:0;border-radius:12px;font-weight:900}.tw22go{background:#22c55e}.tw22map{height:55vh;min-height:420px}.tw22p{background:#fff;border-radius:18px 18px 0 0;margin-top:-14px;position:relative;z-index:10;padding:12px}.tw22stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.tw22stat{background:#1f2937;color:white;border-radius:10px;padding:7px;text-align:center}.tw22stat b{display:block;font-size:16px}.tw22turn{display:flex;gap:10px;align-items:center;background:#111827;color:white;border-radius:14px;padding:10px;margin-bottom:8px}.tw22arrow{font-size:38px;min-width:44px;text-align:center}.tw22grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.tw22card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:11px;padding:9px}.tw22small{font-size:11px;color:#64748b}.tw22ok,.tw22warn,.tw22bad{padding:9px;border-radius:10px;margin:7px 0;font-weight:800}.tw22ok{background:#dcfce7;color:#166534}.tw22warn{background:#fef3c7;color:#92400e}.tw22bad{background:#fee2e2;color:#991b1b}.tw22chips{display:flex;gap:6px;overflow:auto;padding:7px 0}.tw22chips button{white-space:nowrap}.tw22modal{position:fixed;inset:0;background:#0008;z-index:9999;display:flex;align-items:flex-end}.tw22sheet{background:#fff;width:100%;max-height:88vh;overflow:auto;border-radius:20px 20px 0 0;padding:16px}.tw22list{display:grid;gap:6px}.tw22item{border:1px solid #e2e8f0;border-radius:10px;padding:9px}.tw22report{position:fixed;right:12px;bottom:95px;z-index:600;width:58px;height:58px;border:0;border-radius:50%;background:#f97316;color:#fff;font-size:24px;box-shadow:0 4px 14px #0006}@media(max-width:650px){.tw22stats{grid-template-columns:repeat(2,1fr)}.tw22grid{grid-template-columns:1fr 1fr}.tw22map{height:52vh}}`;document.head.appendChild(s)}
function render(){let r=Q('route');if(!r)return;r.className+=' tw22';r.innerHTML=`<div class="tw22top"><div class="tw22search"><input id="tw22dest" placeholder="Where to? address, city, ZIP"><button id="tw22go" class="tw22b tw22go">GO</button><button id="tw22menu" class="tw22b">☰</button></div><div><span class="twpill" id="tw22speed">-- MPH</span><span class="twpill" id="tw22hos">HOS --</span><span class="twpill" id="tw22air">150 AIR --</span><span class="twpill" id="tw22gps">GPS --</span></div></div><div id="tw22map" class="tw22map"></div><div class="tw22p"><div class="tw22turn"><div id="tw22arrow" class="tw22arrow">⬆️</div><div><b id="tw22next">Enter a destination</b><div id="tw22dist" class="tw22small">Truck navigation ready</div></div></div><div class="tw22stats"><div class="tw22stat"><small>ETA</small><b id="tw22eta">--</b></div><div class="tw22stat"><small>DISTANCE</small><b id="tw22miles">--</b></div><div class="tw22stat"><small>HOS ETA</small><b id="tw22hoseta">--</b></div><div class="tw22stat"><small>ARRIVAL</small><b id="tw22arrival">--</b></div></div><div class="tw22chips"><button id="tw22voice" class="tw22b">🔊 Voice</button><button id="tw22intel" class="tw22b">⚠️ Intel</button><button id="tw22traffic" class="tw22b">🚦 Traffic</button><button id="tw22truck" class="tw22b">🚛 Truck</button><button id="tw22stops" class="tw22b">🛑 Stops</button></div><div id="tw22alerts"></div><div class="tw22chips"><button data-twstop="fuel" class="tw22b">⛽ Fuel</button><button data-twstop="parking" class="tw22b">🅿️ Parking</button><button data-twstop="rest" class="tw22b">🛏️ Rest</button><button data-twstop="repair" class="tw22b">🔧 Repair</button><button data-twstop="scale" class="tw22b">⚖️ Scale</button></div><div class="tw22small">TruckWaze prototype • verify posted clearances, weights, hazmat restrictions, road closures and local rules.</div></div><button id="tw22report" class="tw22report">⚠️</button>`;init()}
function init(){if(!window.L||n.map)return;n.map=L.map('tw22map',{zoomControl:false}).setView([39.5,-98.35],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(n.map);n.map.on('dragstart',()=>n.follow=false);bind();gps()}
function bind(){Q('tw22go').onclick=route;Q('tw22dest').onkeydown=e=>{if(e.key==='Enter')route()};Q('tw22voice').onclick=()=>{n.voice=!n.voice;Q('tw22voice').textContent=n.voice?'🔊 Voice':'🔇 Muted';if(n.voice)say('Voice navigation on')};Q('tw22intel').onclick=()=>intel();Q('tw22traffic').onclick=()=>traffic();Q('tw22truck').onclick=()=>truck();Q('tw22stops').onclick=()=>stops('parking');Q('tw22menu').onclick=menu;Q('tw22report').onclick=report;document.querySelectorAll('[data-twstop]').forEach(b=>b.onclick=()=>stops(b.dataset.twstop))}
function gps(){if(!navigator.geolocation)return; n.watch=navigator.geolocation.watchPosition(p=>{n.pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:(p.coords.speed||0)*2.236936,heading:p.coords.heading,accuracy:p.coords.accuracy||0};let s=get();s.pos=n.pos;put(s);if(!n.marker)n.marker=L.marker([n.pos.lat,n.pos.lon]).addTo(n.map);else n.marker.setLatLng([n.pos.lat,n.pos.lon]);Q('tw22speed').textContent=Math.round(n.pos.speed)+' MPH';Q('tw22gps').textContent='GPS ±'+Math.round(n.pos.accuracy)+'m';radius();navUpdate();if(n.follow)n.map.setView([n.pos.lat,n.pos.lon],Math.max(15,n.map.getZoom()),{animate:true})},e=>{Q('tw22gps').textContent='GPS unavailable';Q('tw22alerts').innerHTML='<div class="tw22bad">📍 GPS unavailable. Enable iPhone Location or continue without live position.</div>'},{enableHighAccuracy:true,maximumAge:1500,timeout:10000})}
function km(a,b,c,d){let R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function radius(){let s=get(),b=s.baseCoords;if(!n.pos)return;if(!b){Q('tw22air').textContent='150 AIR SET BASE';return}let m=km(n.pos.lat,n.pos.lon,b.lat,b.lon)*.621371;Q('tw22air').textContent='150 AIR '+(m<=172.6?'IN':'OUT')+' '+m.toFixed(1)+'mi'}
async function geocode(x){let r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q='+encodeURIComponent(x),{headers:{'Accept-Language':'en-US'}});let a=await r.json();if(!a[0])throw Error('Destination not found');return{lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name}}
async function route(){let text=Q('tw22dest').value.trim(),p=n.pos||get().pos;if(!text||!p)return;try{Q('tw22next').textContent='Building route…';let d=await geocode(text);n.dest=d;let u=`https://router.project-osrm.org/route/v1/driving/${p.lon},${p.lat};${d.lon},${d.lat}?overview=full&geometries=geojson&steps=true&alternatives=true`;let j=await fetch(u).then(r=>r.json());if(j.code!=='Ok')throw Error('Routing unavailable');n.route=j.routes[0];n.steps=n.route.legs.flatMap(x=>x.steps||[]).filter(x=>x.maneuver?.type!=='depart');n.i=0;if(n.layer)n.map.removeLayer(n.layer);n.layer=L.geoJSON(n.route.geometry,{style:{weight:7,opacity:.9}}).addTo(n.map);n.map.fitBounds(n.layer.getBounds(),{padding:[20,150]});let s=get();s.routeEnd=d.name;s.routeMiles=n.route.distance/1609.344;s.routeMinutes=n.route.duration/60;s.routeGeoJSON=n.route.geometry;s.routeSteps=n.steps;put(s);summary();say('Navigation started. '+next())}catch(e){Q('tw22next').textContent=e.message||'Route failed'}}
function hos(){let s=get(),d=Number(s.driveRemaining),w=Number(s.shiftRemaining);return{drive:isFinite(d)?Math.max(0,d):11,shift:isFinite(w)?Math.max(0,w):14}}
function hosSec(sec){let h=hos(),drive=sec/3600,usable=Math.min(h.drive,h.shift);if(drive<=usable)return sec;let total=sec;while(drive>usable){total+=1800;drive-=usable;usable=Math.min(11,14)}return total}
function clock(d){return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function summary(){let r=n.route,m=r.distance/1609.344,e=new Date(Date.now()+r.duration*1000),he=new Date(Date.now()+hosSec(r.duration)*1000);Q('tw22miles').textContent=m.toFixed(1)+' mi';Q('tw22eta').textContent=clock(e);Q('tw22arrival').textContent=clock(e);Q('tw22hoseta').textContent=clock(he);Q('tw22hos').textContent='HOS '+Math.floor(hos().drive)+':'+String(Math.round(hos().drive%1*60)).padStart(2,'0');Q('tw22next').textContent=next();Q('tw22dist').textContent=stepDist();intel()}
function next(){let x=n.steps[n.i];if(!x)return'Continue on route';let m=x.maneuver||{},t=m.type||'continue',mod=(m.modifier||'').replace('-',' '),v=t==='turn'?'Turn':t==='merge'?'Merge':t==='fork'?'Keep':t==='on ramp'?'Take ramp':t==='off ramp'?'Take exit':t==='roundabout'?`At roundabout, take ${m.exit||'the'} exit`:'Continue';return `${v}${mod?' '+mod:''}${x.name?' onto '+x.name:''}`}
function stepDist(){let x=n.steps[n.i],c=x?.maneuver?.location;if(!c||!n.pos)return'';let m=km(n.pos.lat,n.pos.lon,c[1],c[0])*.621371;return m<1?Math.round(m*5280)+' ft':m.toFixed(1)+' mi'}
function navUpdate(){if(!n.route||!n.pos)return;let x=n.steps[n.i],c=x?.maneuver?.location,d=c?km(n.pos.lat,n.pos.lon,c[1],c[0])*.621371:99;if(d<.02&&n.i<n.steps.length-1){n.i++;n.lastSay=0}Q('tw22next').textContent=next();Q('tw22dist').textContent=stepDist();Q('tw22arrow').textContent=({'left':'↰','right':'↱','slight left':'↖️','slight right':'↗️','sharp left':'⬅️','sharp right':'➡️','straight':'⬆️'}[x?.maneuver?.modifier]||'⬆️');if(d<.15&&Date.now()-n.lastSay>12000){say(next()+' in '+stepDist());n.lastSay=Date.now()}if(offset()>0.11&&Date.now()-n.lastReroute>45000){n.lastReroute=Date.now();say('Off route. Recalculating.');route()}}
function offset(){if(!n.route||!n.pos)return 0;let a=n.route.geometry.coordinates,b=Infinity,step=Math.max(1,Math.floor(a.length/300));for(let i=0;i<a.length;i+=step)b=Math.min(b,km(n.pos.lat,n.pos.lon,a[i][1],a[i][0])*.621371);return b}
function say(t){if(!n.voice||!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=1;u.volume=1;speechSynthesis.speak(u)}
async function stops(type){if(!n.pos)return alert('GPS needed for nearby stops.');let tag=type==='fuel'?'amenity=fuel':type==='parking'?'amenity=parking':type==='rest'?'highway=rest_area':type==='repair'?'shop=car_repair':'amenity=parking';let qstr=`[out:json][timeout:15];(node[${tag}](around:30000,${n.pos.lat},${n.pos.lon});way[${tag}](around:30000,${n.pos.lat},${n.pos.lon}););out center tags;`;try{let j=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:qstr}).then(r=>r.json()),a=(j.elements||[]).map(e=>{let lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;return{lat,lon,name:e.tags?.name||type,d:km(n.pos.lat,n.pos.lon,lat,lon)}}).filter(x=>x.lat).sort((a,b)=>a.d-b.d).slice(0,15);sheet('🛑 '+type,a.map(x=>`<div class="tw22item"><b>${esc(x.name)}</b><div class="tw22small">${(x.d*.621371).toFixed(1)} mi away</div><button onclick="open('https://www.google.com/maps/search/?api=1&query=${x.lat},${x.lon}','_blank')">NAVIGATE</button></div>`).join('')||'No results')}catch{sheet('Stops','<div class="tw22bad">Stop search unavailable.</div>')}}
function report(){sheet('⚠️ Truck report',`<p class="tw22small">Local prototype reports are stored on this phone. A shared backend is required for Waze-style community reports.</p><div class="tw22grid">${['accident','construction','closure','pothole','truck hazard','low clearance','police','traffic','weather','parking full','scale','debris'].map(x=>`<button class="tw22b" onclick="TW22.report('${x}')">${x}</button>`).join('')}</div>`)}
function saveReport(t){let s=get();s.driverReports=s.driverReports||[];s.driverReports.unshift({type:t,lat:n.pos?.lat,lon:n.pos?.lon,time:new Date().toISOString()});s.driverReports=s.driverReports.slice(0,100);put(s);document.querySelector('.tw22modal')?.remove();Q('tw22alerts').innerHTML='<div class="tw22ok">📣 '+esc(t)+' reported and saved locally.</div>';say(t+' reported')}
function intel(){let s=get();Q('tw22alerts').innerHTML=`<div class="tw22ok">🧭 Route intelligence active • HOS ${hos().drive.toFixed(1)}h drive / ${hos().shift.toFixed(1)}h window</div><div class="tw22warn">🚛 Public routing is ordinary vehicle routing. Verify bridge clearance, weight, axle, hazmat and local truck restrictions.</div>${s.height?`<div class="tw22card">📏 Height profile: <b>${esc(s.height)}</b></div>`:''}`;weather()}
async function weather(){if(!n.dest)return;try{let p=await fetch(`https://api.weather.gov/points/${n.dest.lat},${n.dest.lon}`).then(r=>r.json()),f=await fetch(p.properties.forecast).then(r=>r.json()),x=f.properties.periods[0];Q('tw22alerts').innerHTML+=`<div class="tw22card">🌦️ Destination: ${esc(x.temperature)}°${esc(x.temperatureUnit)} • ${esc(x.shortForecast)} • wind ${esc(x.windSpeed)} ${esc(x.windDirection)}</div>`}catch{}}
function traffic(){sheet('🚦 Live road intelligence',`<div class="tw22list"><div class="tw22item">🚦 Traffic: a real-time traffic provider is required; OSRM does not supply live congestion.</div><div class="tw22item">🚧 Construction: compatible DOT 511/WZDx feeds can be connected by state.</div><div class="tw22item">🌨️ Weather: NWS destination forecast is available without a paid key.</div><div class="tw22item">🔑 Road511 can be added later with a server-side/API-key architecture; never put a private key in GitHub Pages JavaScript.</div></div>`)}
function truck(){let s=get();sheet('🚛 Truck profile',`<div class="tw22grid"><label>Height<input id="twh" value="${esc(s.height||'')}"></label><label>Width<input id="tww" value="${esc(s.width||'')}"></label><label>Length<input id="twl" value="${esc(s.length||'')}"></label><label>Weight<input id="twg" value="${esc(s.weight||'')}"></label><label>Axles<input id="twa" value="${esc(s.axles||'')}"></label><label>Trailer<input id="twt" value="${esc(s.trailer||'')}"></label></div><button id="twsave" class="tw22b tw22go">SAVE PROFILE</button>`);Q('twsave').onclick=()=>{s=get();Object.assign(s,{height:Q('twh').value,width:Q('tww').value,length:Q('twl').value,weight:Q('twg').value,axles:Q('twa').value,trailer:Q('twt').value});put(s);document.querySelector('.tw22modal')?.remove();intel()}}
function menu(){let s=get();sheet('⚙️ TruckWaze',`<div class="tw22list"><div class="tw22item"><b>Voice:</b> ${n.voice?'ON':'OFF'}</div><div class="tw22item"><b>Local driver reports:</b> ${(s.driverReports||[]).length}</div><div class="tw22item"><b>Open data:</b> OpenStreetMap, OSRM, Overpass, NWS.</div><div class="tw22item"><b>Next integrations:</b> DOT 511/WZDx, live traffic, parking availability, fuel prices, weigh-station status, truck restrictions, community cloud reports.</div><div class="tw22bad">Prototype only — not an FMCSA-certified ELD or guaranteed truck-safe navigation.</div></div>`)}
function sheet(title,body){let m=document.createElement('div');m.className='tw22modal';m.innerHTML=`<div class="tw22sheet"><h2>${title}</h2>${body}<br><button id="tw22close" class="tw22b">CLOSE</button></div>`;document.body.appendChild(m);Q('tw22close').onclick=()=>m.remove()}
window.TW22={report:saveReport};
function install(){style();let b=document.querySelector('nav [data-tab="route"]');if(b)b.textContent='🚛 TRUCKWAZE';let r=Q('route');if(r){setTimeout(render,200)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,700));else setTimeout(install,700);
})();