(()=>{
'use strict';
const KEY='hos150v13', $=id=>document.getElementById(id), get=()=>JSON.parse(localStorage.getItem(KEY)||'{}'), put=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function settings(){let s=get();s.settings=s.settings||{temp:'F',distance:'mi',aiMode:'balanced',aiAlerts:true,voice:true,navMode:'truck',avoidTolls:false,avoidHighways:false,night:false,parkingRadius:25,fuelReserve:20};return s}
function saveSettings(s){put(s)}
function injectSettings(){const sec=document.getElementById('settings');if(!sec||document.getElementById('ultimateSettings'))return;const c=document.createElement('div');c.className='card';c.id='ultimateSettings';c.innerHTML=`<h2>⚙️ Ultimate Driver Preferences</h2><div class="grid g3">
<label>Weather units<select id="unitTemp"><option value="F">°F Fahrenheit</option><option value="C">°C Celsius</option></select></label>
<label>Distance units<select id="unitDistance"><option value="mi">Miles</option><option value="km">Kilometers</option></select></label>
<label>Navigation profile<select id="navMode"><option value="truck">Truck / Tractor-Trailer</option><option value="straight">Straight Truck</option><option value="car">Car / Personal</option></select></label>
<label>AI Copilot<select id="aiMode"><option value="balanced">Balanced</option><option value="safety">Safety-first</option><option value="fuel">Fuel economy</option><option value="schedule">On-time delivery</option><option value="quiet">Quiet / on request</option></select></label>
<label>Parking search radius<select id="parkingRadius"><option>10</option><option>25</option><option>50</option><option>100</option></select></label>
<label>Fuel reserve %<input id="fuelReserve" type="number" min="5" max="50"></label>
</div><div class="row"><button id="saveUltimateSettings">SAVE PREFERENCES</button><button id="voiceCmd" class="secondary">🎙️ VOICE COMMAND</button><button id="aiBrief" class="secondary">🤖 AI TRIP BRIEF</button></div><div class="row"><label><input id="aiAlerts" type="checkbox"> Proactive AI warnings</label><label><input id="voiceEnabled" type="checkbox"> Voice features</label><label><input id="nightMode" type="checkbox"> Night driving mode</label><label><input id="avoidTolls" type="checkbox"> Prefer avoiding tolls</label><label><input id="avoidHighways" type="checkbox"> Avoid highways</label></div><div id="aiSettingsMsg" class="status neutral">Preferences are stored on this device.</div>`;sec.appendChild(c);const s=settings();$('unitTemp').value=s.settings.temp;$('unitDistance').value=s.settings.distance;$('navMode').value=s.settings.navMode;$('aiMode').value=s.settings.aiMode;$('parkingRadius').value=s.settings.parkingRadius;$('fuelReserve').value=s.settings.fuelReserve;$('aiAlerts').checked=!!s.settings.aiAlerts;$('voiceEnabled').checked=!!s.settings.voice;$('nightMode').checked=!!s.settings.night;$('avoidTolls').checked=!!s.settings.avoidTolls;$('avoidHighways').checked=!!s.settings.avoidHighways;
$('saveUltimateSettings').onclick=()=>{let x=get();x.settings={temp:$('unitTemp').value,distance:$('unitDistance').value,navMode:$('navMode').value,aiMode:$('aiMode').value,parkingRadius:+$('parkingRadius').value,fuelReserve:+$('fuelReserve').value,aiAlerts:$('aiAlerts').checked,voice:$('voiceEnabled').checked,night:$('nightMode').checked,avoidTolls:$('avoidTolls').checked,avoidHighways:$('avoidHighways').checked};put(x);applyNight(x.settings.night);$('aiSettingsMsg').className='status good';$('aiSettingsMsg').textContent='Saved. Weather and trip tools will use these preferences.';renderEnhancedWeather()};$('voiceCmd').onclick=voiceCommand;$('aiBrief').onclick=aiBrief;applyNight(s.settings.night)}
function applyNight(on){document.body.classList.toggle('night',!!on)}
function injectTripTools(){const sec=document.getElementById('trip');if(!sec||document.getElementById('truckRoutePanel'))return;const c=document.createElement('div');c.className='card';c.id='truckRoutePanel';c.innerHTML=`<h2>🛰️ Truck Route & Arrival Tools</h2><div class="grid g3"><label>Trailer length (ft)<input id="trailerLength" type="number"></label><label>Truck width (ft)<input id="truckWidth" type="number" step=".1"></label><label>Clearance (ft)<input id="truckClearance" type="number" step=".1"></label><label>Gross weight (lb)<input id="routeWeight" type="number"></label><label>Axles<input id="routeAxles" type="number"></label><label>Hazmat<select id="routeHazmat"><option value="no">No</option><option value="yes">Yes</option></select></label></div><div class="row"><button id="navigateRoute">🧭 START NAVIGATION</button><button id="arrivalPlan" class="secondary">📍 ARRIVAL PLAN</button><button id="routeShare" class="secondary">↗️ SHARE ROUTE</button></div><div id="truckRouteMsg" class="status neutral">Enter a destination and plan a route. This preview uses public road-routing data; it is not certified commercial-truck routing.</div></div>`;sec.appendChild(c);let s=get(),p=s.profile||{};$('trailerLength').value=p.trailerLength||'';$('truckWidth').value=p.width||'';$('truckClearance').value=p.clearance||p.height||'';$('routeWeight').value=p.weight||'';$('routeAxles').value=p.axles||'';$('routeHazmat').value=p.hazmat||'no';$('navigateRoute').onclick=()=>{let d=$('destination')?.value.trim();if(!d)return alert('Enter a destination first.');let url='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(d)+'&travelmode=driving';window.open(url,'_blank')};$('arrivalPlan').onclick=arrivalPlan;$('routeShare').onclick=()=>{let d=$('destination')?.value.trim();if(!d)return;let text=`Driver Companion route: ${d}`;navigator.share?navigator.share({title:'Driver Companion Route',text}):navigator.clipboard?.writeText(text).then(()=>alert('Route note copied.'))}};
async function geocode(q){let r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q));let a=await r.json();if(!a[0])throw Error('Destination not found');return{lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name}}
async function enhancedWeather(lat,lon){const s=settings().settings;const u=s.temp==='C'?'&temperature_unit=celsius':'&temperature_unit=fahrenheit';const j=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,precipitation,wind_speed_10m,weather_code&hourly=temperature_2m,precipitation_probability,wind_speed_10m,weather_code&forecast_days=3${u}`).then(r=>r.json());return j}
function weatherLabel(code){const m={0:'Clear',1:'Mainly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm/hail',99:'Severe thunderstorm'};return m[code]||'Weather'}
async function renderEnhancedWeather(){let el=document.getElementById('enhancedWeather');if(!el)return;let q=$('weatherPlace')?.value.trim()||$('destination')?.value.trim();try{let p;if(q)p=await geocode(q);else{let s=get();p=s.pos?{lat:s.pos.lat,lon:s.pos.lon,name:'Current GPS'}:null}if(!p){el.className='status neutral';el.textContent='Enter a city/ZIP or enable GPS.';return}let j=await enhancedWeather(p.lat,p.lon);const u=settings().settings.temp==='C'?'°C':'°F';el.className='status blue';el.innerHTML=`<b>${esc(p.name)}</b><br>🌡️ ${Math.round(j.current.temperature_2m)}${u} feels ${Math.round(j.current.apparent_temperature)}${u} • 💨 ${Math.round(j.current.wind_speed_10m)} ${settings().settings.distance==='km'?'km/h':'mph'} • ${weatherLabel(j.current.weather_code)}<br>🌧️ Precipitation ${j.current.precipitation} ${j.current_units.precipitation}`; }catch(e){el.className='status bad';el.textContent='Weather unavailable right now.'}}
function injectWeather(){const sec=document.getElementById('weather');if(!sec||document.getElementById('enhancedWeatherCard'))return;const c=document.createElement('div');c.className='card';c.id='enhancedWeatherCard';c.innerHTML='<h2>🌡️ Driver Weather Display</h2><div id="enhancedWeather" class="status neutral">Weather uses your selected °F/°C preference.</div><p class="muted">Wind, precipitation and temperature are shown for the selected location. Route weather is advisory.</p>';sec.insertBefore(c,sec.firstElementChild);$('getWeather')?.addEventListener('click',()=>setTimeout(renderEnhancedWeather,100));$('weatherHere')?.addEventListener('click',()=>setTimeout(renderEnhancedWeather,100));renderEnhancedWeather()}
function aiContext(){let s=get(),p=s.profile||{},m=s.base&&s.pos?null:null;return{driver:p.driver||'',truck:p.unit||'',destination:$('destination')?.value||s.routeEnd||'',roadMiles:s.routeMiles||null,eta:$('eta')?.textContent||null,fuelPct:p.fuelPct||'',mpg:p.mpg||'',tank:p.tanks||'',status:s.status||'OFF DUTY',aiMode:(s.settings||{}).aiMode||'balanced'}}
function aiBrief(){const c=aiContext(),mode=c.aiMode;let tips=[];if(c.destination)tips.push(`Destination: ${c.destination}.`);if(c.roadMiles)tips.push(`Route: ${Math.round(c.roadMiles)} road miles; current app ETA: ${c.eta||'calculating'}.`);if(c.fuelPct&&c.mpg&&c.tank)tips.push(`Fuel profile: ${c.fuelPct}% of ${c.tank} gal at ${c.mpg} MPG.`);tips.push(`AI mode: ${mode}.`);tips.push('Verify truck restrictions, posted signs, HOS requirements and weather before acting.');let prompt=`You are my professional truck-driver copilot. Give me a concise actionable trip brief using this data: ${JSON.stringify(c)}. Focus on ${mode}. Do not claim an HOS exemption or truck-safe route unless verified.`;if(navigator.clipboard)navigator.clipboard.writeText(prompt).catch(()=>{});window.open('https://chatgpt.com/?q='+encodeURIComponent(prompt),'_blank');let el=$('aiSettingsMsg');if(el){el.className='status good';el.textContent=tips.join(' ')} }
function voiceCommand(){let s=settings().settings;if(!s.voice)return alert('Enable Voice features in Settings first.');if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return alert('Voice recognition is not supported in this browser.');const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='en-US';r.interimResults=false;r.onresult=e=>{let t=e.results[0][0].transcript.toLowerCase();if(t.includes('weather')){document.querySelector('[data-tab="weather"]')?.click();renderEnhancedWeather()}else if(t.includes('parking')){window.open('https://www.google.com/maps/search/truck+parking/','_blank')}else if(t.includes('fuel')){window.open('https://www.google.com/maps/search/truck+fuel/','_blank')}else if(t.includes('navigate')||t.includes('destination'))document.querySelector('[data-tab="trip"]')?.click();else if(t.includes('ai')||t.includes('brief'))aiBrief();else alert('I heard: '+t)};r.start()}
function arrivalPlan(){let d=$('destination')?.value.trim();if(!d)return alert('Enter a destination first.');alert('Arrival planning: use the destination map view to identify truck entrances, docks, staging and parking. This prototype cannot verify private-property truck access.');}
function boot(){injectSettings();injectTripTools();injectWeather();const s=settings();applyNight(s.settings.night);window.addEventListener('online',renderEnhancedWeather);setInterval(()=>{if(document.getElementById('weather')?.classList.contains('active'))renderEnhancedWeather()},300000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();